// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.optimizer.v1.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {
}
