// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.optimizer.v1.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "healthy" or "starting"
   * </pre>
   *
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * "healthy" or "starting"
   * </pre>
   *
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>bool ready = 2;</code>
   * @return The ready.
   */
  boolean getReady();

  /**
   * <code>int32 q_table_states = 3;</code>
   * @return The qTableStates.
   */
  int getQTableStates();

  /**
   * <code>int32 experience_count = 4;</code>
   * @return The experienceCount.
   */
  int getExperienceCount();

  /**
   * <code>string version = 5;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 5;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
