// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

public interface PredictRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.optimizer.v1.PredictRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Table row count (page count as proxy)
   * </pre>
   *
   * <code>int32 num_rows = 1;</code>
   * @return The numRows.
   */
  int getNumRows();

  /**
   * <pre>
   * Is this a range predicate (BETWEEN)?
   * </pre>
   *
   * <code>bool is_range = 2;</code>
   * @return The isRange.
   */
  boolean getIsRange();

  /**
   * <pre>
   * Does an index exist on predicate column?
   * </pre>
   *
   * <code>bool has_index = 3;</code>
   * @return The hasIndex.
   */
  boolean getHasIndex();

  /**
   * <pre>
   * 0=equality, 1=narrow_range, 2=wide_range
   * </pre>
   *
   * <code>int32 predicate_type = 4;</code>
   * @return The predicateType.
   */
  int getPredicateType();

  /**
   * <pre>
   * Estimated matching rows
   * </pre>
   *
   * <code>int32 estimated_matches = 5;</code>
   * @return The estimatedMatches.
   */
  int getEstimatedMatches();

  /**
   * <pre>
   * Correlation ID for tracing
   * </pre>
   *
   * <code>string request_id = 6;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * Correlation ID for tracing
   * </pre>
   *
   * <code>string request_id = 6;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();
}
