// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

/**
 * Protobuf type {@code minipostgres.optimizer.v1.PredictResponse}
 */
public final class PredictResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.optimizer.v1.PredictResponse)
    PredictResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PredictResponse.class.getName());
  }
  // Use PredictResponse.newBuilder() to construct.
  private PredictResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PredictResponse() {
    stateKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.optimizer.v1.PredictResponse.class, database.kernel.grpc.optimizer.v1.PredictResponse.Builder.class);
  }

  public static final int ACTION_FIELD_NUMBER = 1;
  private int action_ = 0;
  /**
   * <pre>
   * 0=SeqScan, 1=IndexScan
   * </pre>
   *
   * <code>int32 action = 1;</code>
   * @return The action.
   */
  @java.lang.Override
  public int getAction() {
    return action_;
  }

  public static final int STATE_KEY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stateKey_ = "";
  /**
   * <pre>
   * Encoded state key for debugging
   * </pre>
   *
   * <code>string state_key = 2;</code>
   * @return The stateKey.
   */
  @java.lang.Override
  public java.lang.String getStateKey() {
    java.lang.Object ref = stateKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stateKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Encoded state key for debugging
   * </pre>
   *
   * <code>string state_key = 2;</code>
   * @return The bytes for stateKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStateKeyBytes() {
    java.lang.Object ref = stateKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stateKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (action_ != 0) {
      output.writeInt32(1, action_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stateKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, stateKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (action_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, action_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stateKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, stateKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.optimizer.v1.PredictResponse)) {
      return super.equals(obj);
    }
    database.kernel.grpc.optimizer.v1.PredictResponse other = (database.kernel.grpc.optimizer.v1.PredictResponse) obj;

    if (getAction()
        != other.getAction()) return false;
    if (!getStateKey()
        .equals(other.getStateKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction();
    hash = (37 * hash) + STATE_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getStateKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.optimizer.v1.PredictResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.optimizer.v1.PredictResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.optimizer.v1.PredictResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.optimizer.v1.PredictResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.optimizer.v1.PredictResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.optimizer.v1.PredictResponse)
      database.kernel.grpc.optimizer.v1.PredictResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.optimizer.v1.PredictResponse.class, database.kernel.grpc.optimizer.v1.PredictResponse.Builder.class);
    }

    // Construct using database.kernel.grpc.optimizer.v1.PredictResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      action_ = 0;
      stateKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictResponse_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.PredictResponse getDefaultInstanceForType() {
      return database.kernel.grpc.optimizer.v1.PredictResponse.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.PredictResponse build() {
      database.kernel.grpc.optimizer.v1.PredictResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.PredictResponse buildPartial() {
      database.kernel.grpc.optimizer.v1.PredictResponse result = new database.kernel.grpc.optimizer.v1.PredictResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(database.kernel.grpc.optimizer.v1.PredictResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.action_ = action_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stateKey_ = stateKey_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.optimizer.v1.PredictResponse) {
        return mergeFrom((database.kernel.grpc.optimizer.v1.PredictResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.optimizer.v1.PredictResponse other) {
      if (other == database.kernel.grpc.optimizer.v1.PredictResponse.getDefaultInstance()) return this;
      if (other.getAction() != 0) {
        setAction(other.getAction());
      }
      if (!other.getStateKey().isEmpty()) {
        stateKey_ = other.stateKey_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              action_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              stateKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int action_ ;
    /**
     * <pre>
     * 0=SeqScan, 1=IndexScan
     * </pre>
     *
     * <code>int32 action = 1;</code>
     * @return The action.
     */
    @java.lang.Override
    public int getAction() {
      return action_;
    }
    /**
     * <pre>
     * 0=SeqScan, 1=IndexScan
     * </pre>
     *
     * <code>int32 action = 1;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(int value) {

      action_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0=SeqScan, 1=IndexScan
     * </pre>
     *
     * <code>int32 action = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000001);
      action_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object stateKey_ = "";
    /**
     * <pre>
     * Encoded state key for debugging
     * </pre>
     *
     * <code>string state_key = 2;</code>
     * @return The stateKey.
     */
    public java.lang.String getStateKey() {
      java.lang.Object ref = stateKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stateKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Encoded state key for debugging
     * </pre>
     *
     * <code>string state_key = 2;</code>
     * @return The bytes for stateKey.
     */
    public com.google.protobuf.ByteString
        getStateKeyBytes() {
      java.lang.Object ref = stateKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stateKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Encoded state key for debugging
     * </pre>
     *
     * <code>string state_key = 2;</code>
     * @param value The stateKey to set.
     * @return This builder for chaining.
     */
    public Builder setStateKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stateKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encoded state key for debugging
     * </pre>
     *
     * <code>string state_key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStateKey() {
      stateKey_ = getDefaultInstance().getStateKey();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encoded state key for debugging
     * </pre>
     *
     * <code>string state_key = 2;</code>
     * @param value The bytes for stateKey to set.
     * @return This builder for chaining.
     */
    public Builder setStateKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stateKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.optimizer.v1.PredictResponse)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.optimizer.v1.PredictResponse)
  private static final database.kernel.grpc.optimizer.v1.PredictResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.optimizer.v1.PredictResponse();
  }

  public static database.kernel.grpc.optimizer.v1.PredictResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictResponse>
      PARSER = new com.google.protobuf.AbstractParser<PredictResponse>() {
    @java.lang.Override
    public PredictResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PredictResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.optimizer.v1.PredictResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

