// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

/**
 * Protobuf type {@code minipostgres.optimizer.v1.PredictRequest}
 */
public final class PredictRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.optimizer.v1.PredictRequest)
    PredictRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PredictRequest.class.getName());
  }
  // Use PredictRequest.newBuilder() to construct.
  private PredictRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PredictRequest() {
    requestId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.optimizer.v1.PredictRequest.class, database.kernel.grpc.optimizer.v1.PredictRequest.Builder.class);
  }

  public static final int NUM_ROWS_FIELD_NUMBER = 1;
  private int numRows_ = 0;
  /**
   * <pre>
   * Table row count (page count as proxy)
   * </pre>
   *
   * <code>int32 num_rows = 1;</code>
   * @return The numRows.
   */
  @java.lang.Override
  public int getNumRows() {
    return numRows_;
  }

  public static final int IS_RANGE_FIELD_NUMBER = 2;
  private boolean isRange_ = false;
  /**
   * <pre>
   * Is this a range predicate (BETWEEN)?
   * </pre>
   *
   * <code>bool is_range = 2;</code>
   * @return The isRange.
   */
  @java.lang.Override
  public boolean getIsRange() {
    return isRange_;
  }

  public static final int HAS_INDEX_FIELD_NUMBER = 3;
  private boolean hasIndex_ = false;
  /**
   * <pre>
   * Does an index exist on predicate column?
   * </pre>
   *
   * <code>bool has_index = 3;</code>
   * @return The hasIndex.
   */
  @java.lang.Override
  public boolean getHasIndex() {
    return hasIndex_;
  }

  public static final int PREDICATE_TYPE_FIELD_NUMBER = 4;
  private int predicateType_ = 0;
  /**
   * <pre>
   * 0=equality, 1=narrow_range, 2=wide_range
   * </pre>
   *
   * <code>int32 predicate_type = 4;</code>
   * @return The predicateType.
   */
  @java.lang.Override
  public int getPredicateType() {
    return predicateType_;
  }

  public static final int ESTIMATED_MATCHES_FIELD_NUMBER = 5;
  private int estimatedMatches_ = 0;
  /**
   * <pre>
   * Estimated matching rows
   * </pre>
   *
   * <code>int32 estimated_matches = 5;</code>
   * @return The estimatedMatches.
   */
  @java.lang.Override
  public int getEstimatedMatches() {
    return estimatedMatches_;
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requestId_ = "";
  /**
   * <pre>
   * Correlation ID for tracing
   * </pre>
   *
   * <code>string request_id = 6;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Correlation ID for tracing
   * </pre>
   *
   * <code>string request_id = 6;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numRows_ != 0) {
      output.writeInt32(1, numRows_);
    }
    if (isRange_ != false) {
      output.writeBool(2, isRange_);
    }
    if (hasIndex_ != false) {
      output.writeBool(3, hasIndex_);
    }
    if (predicateType_ != 0) {
      output.writeInt32(4, predicateType_);
    }
    if (estimatedMatches_ != 0) {
      output.writeInt32(5, estimatedMatches_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, requestId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numRows_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, numRows_);
    }
    if (isRange_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isRange_);
    }
    if (hasIndex_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, hasIndex_);
    }
    if (predicateType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, predicateType_);
    }
    if (estimatedMatches_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, estimatedMatches_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, requestId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.optimizer.v1.PredictRequest)) {
      return super.equals(obj);
    }
    database.kernel.grpc.optimizer.v1.PredictRequest other = (database.kernel.grpc.optimizer.v1.PredictRequest) obj;

    if (getNumRows()
        != other.getNumRows()) return false;
    if (getIsRange()
        != other.getIsRange()) return false;
    if (getHasIndex()
        != other.getHasIndex()) return false;
    if (getPredicateType()
        != other.getPredicateType()) return false;
    if (getEstimatedMatches()
        != other.getEstimatedMatches()) return false;
    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUM_ROWS_FIELD_NUMBER;
    hash = (53 * hash) + getNumRows();
    hash = (37 * hash) + IS_RANGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsRange());
    hash = (37 * hash) + HAS_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasIndex());
    hash = (37 * hash) + PREDICATE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPredicateType();
    hash = (37 * hash) + ESTIMATED_MATCHES_FIELD_NUMBER;
    hash = (53 * hash) + getEstimatedMatches();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.optimizer.v1.PredictRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.optimizer.v1.PredictRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.optimizer.v1.PredictRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.optimizer.v1.PredictRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.optimizer.v1.PredictRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.optimizer.v1.PredictRequest)
      database.kernel.grpc.optimizer.v1.PredictRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.optimizer.v1.PredictRequest.class, database.kernel.grpc.optimizer.v1.PredictRequest.Builder.class);
    }

    // Construct using database.kernel.grpc.optimizer.v1.PredictRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      numRows_ = 0;
      isRange_ = false;
      hasIndex_ = false;
      predicateType_ = 0;
      estimatedMatches_ = 0;
      requestId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_PredictRequest_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.PredictRequest getDefaultInstanceForType() {
      return database.kernel.grpc.optimizer.v1.PredictRequest.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.PredictRequest build() {
      database.kernel.grpc.optimizer.v1.PredictRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.PredictRequest buildPartial() {
      database.kernel.grpc.optimizer.v1.PredictRequest result = new database.kernel.grpc.optimizer.v1.PredictRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(database.kernel.grpc.optimizer.v1.PredictRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.numRows_ = numRows_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isRange_ = isRange_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.hasIndex_ = hasIndex_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.predicateType_ = predicateType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.estimatedMatches_ = estimatedMatches_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.requestId_ = requestId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.optimizer.v1.PredictRequest) {
        return mergeFrom((database.kernel.grpc.optimizer.v1.PredictRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.optimizer.v1.PredictRequest other) {
      if (other == database.kernel.grpc.optimizer.v1.PredictRequest.getDefaultInstance()) return this;
      if (other.getNumRows() != 0) {
        setNumRows(other.getNumRows());
      }
      if (other.getIsRange() != false) {
        setIsRange(other.getIsRange());
      }
      if (other.getHasIndex() != false) {
        setHasIndex(other.getHasIndex());
      }
      if (other.getPredicateType() != 0) {
        setPredicateType(other.getPredicateType());
      }
      if (other.getEstimatedMatches() != 0) {
        setEstimatedMatches(other.getEstimatedMatches());
      }
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              numRows_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              isRange_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              hasIndex_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              predicateType_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              estimatedMatches_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              requestId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int numRows_ ;
    /**
     * <pre>
     * Table row count (page count as proxy)
     * </pre>
     *
     * <code>int32 num_rows = 1;</code>
     * @return The numRows.
     */
    @java.lang.Override
    public int getNumRows() {
      return numRows_;
    }
    /**
     * <pre>
     * Table row count (page count as proxy)
     * </pre>
     *
     * <code>int32 num_rows = 1;</code>
     * @param value The numRows to set.
     * @return This builder for chaining.
     */
    public Builder setNumRows(int value) {

      numRows_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Table row count (page count as proxy)
     * </pre>
     *
     * <code>int32 num_rows = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumRows() {
      bitField0_ = (bitField0_ & ~0x00000001);
      numRows_ = 0;
      onChanged();
      return this;
    }

    private boolean isRange_ ;
    /**
     * <pre>
     * Is this a range predicate (BETWEEN)?
     * </pre>
     *
     * <code>bool is_range = 2;</code>
     * @return The isRange.
     */
    @java.lang.Override
    public boolean getIsRange() {
      return isRange_;
    }
    /**
     * <pre>
     * Is this a range predicate (BETWEEN)?
     * </pre>
     *
     * <code>bool is_range = 2;</code>
     * @param value The isRange to set.
     * @return This builder for chaining.
     */
    public Builder setIsRange(boolean value) {

      isRange_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Is this a range predicate (BETWEEN)?
     * </pre>
     *
     * <code>bool is_range = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsRange() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isRange_ = false;
      onChanged();
      return this;
    }

    private boolean hasIndex_ ;
    /**
     * <pre>
     * Does an index exist on predicate column?
     * </pre>
     *
     * <code>bool has_index = 3;</code>
     * @return The hasIndex.
     */
    @java.lang.Override
    public boolean getHasIndex() {
      return hasIndex_;
    }
    /**
     * <pre>
     * Does an index exist on predicate column?
     * </pre>
     *
     * <code>bool has_index = 3;</code>
     * @param value The hasIndex to set.
     * @return This builder for chaining.
     */
    public Builder setHasIndex(boolean value) {

      hasIndex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Does an index exist on predicate column?
     * </pre>
     *
     * <code>bool has_index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      hasIndex_ = false;
      onChanged();
      return this;
    }

    private int predicateType_ ;
    /**
     * <pre>
     * 0=equality, 1=narrow_range, 2=wide_range
     * </pre>
     *
     * <code>int32 predicate_type = 4;</code>
     * @return The predicateType.
     */
    @java.lang.Override
    public int getPredicateType() {
      return predicateType_;
    }
    /**
     * <pre>
     * 0=equality, 1=narrow_range, 2=wide_range
     * </pre>
     *
     * <code>int32 predicate_type = 4;</code>
     * @param value The predicateType to set.
     * @return This builder for chaining.
     */
    public Builder setPredicateType(int value) {

      predicateType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0=equality, 1=narrow_range, 2=wide_range
     * </pre>
     *
     * <code>int32 predicate_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPredicateType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      predicateType_ = 0;
      onChanged();
      return this;
    }

    private int estimatedMatches_ ;
    /**
     * <pre>
     * Estimated matching rows
     * </pre>
     *
     * <code>int32 estimated_matches = 5;</code>
     * @return The estimatedMatches.
     */
    @java.lang.Override
    public int getEstimatedMatches() {
      return estimatedMatches_;
    }
    /**
     * <pre>
     * Estimated matching rows
     * </pre>
     *
     * <code>int32 estimated_matches = 5;</code>
     * @param value The estimatedMatches to set.
     * @return This builder for chaining.
     */
    public Builder setEstimatedMatches(int value) {

      estimatedMatches_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Estimated matching rows
     * </pre>
     *
     * <code>int32 estimated_matches = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEstimatedMatches() {
      bitField0_ = (bitField0_ & ~0x00000010);
      estimatedMatches_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <pre>
     * Correlation ID for tracing
     * </pre>
     *
     * <code>string request_id = 6;</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Correlation ID for tracing
     * </pre>
     *
     * <code>string request_id = 6;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Correlation ID for tracing
     * </pre>
     *
     * <code>string request_id = 6;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requestId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Correlation ID for tracing
     * </pre>
     *
     * <code>string request_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      requestId_ = getDefaultInstance().getRequestId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Correlation ID for tracing
     * </pre>
     *
     * <code>string request_id = 6;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requestId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.optimizer.v1.PredictRequest)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.optimizer.v1.PredictRequest)
  private static final database.kernel.grpc.optimizer.v1.PredictRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.optimizer.v1.PredictRequest();
  }

  public static database.kernel.grpc.optimizer.v1.PredictRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictRequest>
      PARSER = new com.google.protobuf.AbstractParser<PredictRequest>() {
    @java.lang.Override
    public PredictRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PredictRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.optimizer.v1.PredictRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

