// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

public interface PredictResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.optimizer.v1.PredictResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0=SeqScan, 1=IndexScan
   * </pre>
   *
   * <code>int32 action = 1;</code>
   * @return The action.
   */
  int getAction();

  /**
   * <pre>
   * Encoded state key for debugging
   * </pre>
   *
   * <code>string state_key = 2;</code>
   * @return The stateKey.
   */
  java.lang.String getStateKey();
  /**
   * <pre>
   * Encoded state key for debugging
   * </pre>
   *
   * <code>string state_key = 2;</code>
   * @return The bytes for stateKey.
   */
  com.google.protobuf.ByteString
      getStateKeyBytes();
}
