// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

public final class QueryOptimizerProto {
  private QueryOptimizerProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      QueryOptimizerProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_optimizer_v1_PredictRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_optimizer_v1_PredictRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_optimizer_v1_PredictResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_optimizer_v1_PredictResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_optimizer_v1_RewardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_optimizer_v1_RewardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_optimizer_v1_QueryState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_optimizer_v1_QueryState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_optimizer_v1_RewardResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_optimizer_v1_RewardResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_optimizer_v1_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_optimizer_v1_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_optimizer_v1_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_optimizer_v1_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025query_optimizer.proto\022\031minipostgres.op" +
      "timizer.v1\"\216\001\n\016PredictRequest\022\020\n\010num_row" +
      "s\030\001 \001(\005\022\020\n\010is_range\030\002 \001(\010\022\021\n\thas_index\030\003" +
      " \001(\010\022\026\n\016predicate_type\030\004 \001(\005\022\031\n\021estimate" +
      "d_matches\030\005 \001(\005\022\022\n\nrequest_id\030\006 \001(\t\"4\n\017P" +
      "redictResponse\022\016\n\006action\030\001 \001(\005\022\021\n\tstate_" +
      "key\030\002 \001(\t\"~\n\rRewardRequest\0224\n\005state\030\001 \001(" +
      "\0132%.minipostgres.optimizer.v1.QueryState" +
      "\022\016\n\006action\030\002 \001(\005\022\016\n\006reward\030\003 \001(\001\022\027\n\017idem" +
      "potency_key\030\004 \001(\t\"v\n\nQueryState\022\020\n\010num_r" +
      "ows\030\001 \001(\005\022\020\n\010is_range\030\002 \001(\010\022\021\n\thas_index" +
      "\030\003 \001(\010\022\026\n\016predicate_type\030\004 \001(\005\022\031\n\021estima" +
      "ted_matches\030\005 \001(\005\"\206\001\n\016RewardResponse\022\016\n\006" +
      "status\030\001 \001(\t\022\021\n\told_value\030\002 \001(\001\022\021\n\tnew_v" +
      "alue\030\003 \001(\001\022\031\n\021normalized_reward\030\004 \001(\001\022\017\n" +
      "\007epsilon\030\005 \001(\001\022\022\n\nidempotent\030\006 \001(\010\"\024\n\022He" +
      "althCheckRequest\"w\n\023HealthCheckResponse\022" +
      "\016\n\006status\030\001 \001(\t\022\r\n\005ready\030\002 \001(\010\022\026\n\016q_tabl" +
      "e_states\030\003 \001(\005\022\030\n\020experience_count\030\004 \001(\005" +
      "\022\017\n\007version\030\005 \001(\t2\314\002\n\025QueryOptimizerServ" +
      "ice\022`\n\007Predict\022).minipostgres.optimizer." +
      "v1.PredictRequest\032*.minipostgres.optimiz" +
      "er.v1.PredictResponse\022c\n\014ReportReward\022(." +
      "minipostgres.optimizer.v1.RewardRequest\032" +
      ").minipostgres.optimizer.v1.RewardRespon" +
      "se\022l\n\013HealthCheck\022-.minipostgres.optimiz" +
      "er.v1.HealthCheckRequest\032..minipostgres." +
      "optimizer.v1.HealthCheckResponseB:\n!data" +
      "base.kernel.grpc.optimizer.v1B\023QueryOpti" +
      "mizerProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_minipostgres_optimizer_v1_PredictRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_minipostgres_optimizer_v1_PredictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_optimizer_v1_PredictRequest_descriptor,
        new java.lang.String[] { "NumRows", "IsRange", "HasIndex", "PredicateType", "EstimatedMatches", "RequestId", });
    internal_static_minipostgres_optimizer_v1_PredictResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_minipostgres_optimizer_v1_PredictResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_optimizer_v1_PredictResponse_descriptor,
        new java.lang.String[] { "Action", "StateKey", });
    internal_static_minipostgres_optimizer_v1_RewardRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_minipostgres_optimizer_v1_RewardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_optimizer_v1_RewardRequest_descriptor,
        new java.lang.String[] { "State", "Action", "Reward", "IdempotencyKey", });
    internal_static_minipostgres_optimizer_v1_QueryState_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_minipostgres_optimizer_v1_QueryState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_optimizer_v1_QueryState_descriptor,
        new java.lang.String[] { "NumRows", "IsRange", "HasIndex", "PredicateType", "EstimatedMatches", });
    internal_static_minipostgres_optimizer_v1_RewardResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_minipostgres_optimizer_v1_RewardResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_optimizer_v1_RewardResponse_descriptor,
        new java.lang.String[] { "Status", "OldValue", "NewValue", "NormalizedReward", "Epsilon", "Idempotent", });
    internal_static_minipostgres_optimizer_v1_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_minipostgres_optimizer_v1_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_optimizer_v1_HealthCheckRequest_descriptor,
        new java.lang.String[] { });
    internal_static_minipostgres_optimizer_v1_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_minipostgres_optimizer_v1_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_optimizer_v1_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", "Ready", "QTableStates", "ExperienceCount", "Version", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
