// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

public interface QueryStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.optimizer.v1.QueryState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 num_rows = 1;</code>
   * @return The numRows.
   */
  int getNumRows();

  /**
   * <code>bool is_range = 2;</code>
   * @return The isRange.
   */
  boolean getIsRange();

  /**
   * <code>bool has_index = 3;</code>
   * @return The hasIndex.
   */
  boolean getHasIndex();

  /**
   * <code>int32 predicate_type = 4;</code>
   * @return The predicateType.
   */
  int getPredicateType();

  /**
   * <code>int32 estimated_matches = 5;</code>
   * @return The estimatedMatches.
   */
  int getEstimatedMatches();
}
