// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

/**
 * Protobuf type {@code minipostgres.optimizer.v1.RewardRequest}
 */
public final class RewardRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.optimizer.v1.RewardRequest)
    RewardRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RewardRequest.class.getName());
  }
  // Use RewardRequest.newBuilder() to construct.
  private RewardRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RewardRequest() {
    idempotencyKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.optimizer.v1.RewardRequest.class, database.kernel.grpc.optimizer.v1.RewardRequest.Builder.class);
  }

  private int bitField0_;
  public static final int STATE_FIELD_NUMBER = 1;
  private database.kernel.grpc.optimizer.v1.QueryState state_;
  /**
   * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
   * @return Whether the state field is set.
   */
  @java.lang.Override
  public boolean hasState() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
   * @return The state.
   */
  @java.lang.Override
  public database.kernel.grpc.optimizer.v1.QueryState getState() {
    return state_ == null ? database.kernel.grpc.optimizer.v1.QueryState.getDefaultInstance() : state_;
  }
  /**
   * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.optimizer.v1.QueryStateOrBuilder getStateOrBuilder() {
    return state_ == null ? database.kernel.grpc.optimizer.v1.QueryState.getDefaultInstance() : state_;
  }

  public static final int ACTION_FIELD_NUMBER = 2;
  private int action_ = 0;
  /**
   * <pre>
   * 0=SeqScan, 1=IndexScan
   * </pre>
   *
   * <code>int32 action = 2;</code>
   * @return The action.
   */
  @java.lang.Override
  public int getAction() {
    return action_;
  }

  public static final int REWARD_FIELD_NUMBER = 3;
  private double reward_ = 0D;
  /**
   * <pre>
   * Negative execution time in ms
   * </pre>
   *
   * <code>double reward = 3;</code>
   * @return The reward.
   */
  @java.lang.Override
  public double getReward() {
    return reward_;
  }

  public static final int IDEMPOTENCY_KEY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idempotencyKey_ = "";
  /**
   * <pre>
   * Idempotency key for safe retries
   * </pre>
   *
   * <code>string idempotency_key = 4;</code>
   * @return The idempotencyKey.
   */
  @java.lang.Override
  public java.lang.String getIdempotencyKey() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idempotencyKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Idempotency key for safe retries
   * </pre>
   *
   * <code>string idempotency_key = 4;</code>
   * @return The bytes for idempotencyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdempotencyKeyBytes() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idempotencyKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getState());
    }
    if (action_ != 0) {
      output.writeInt32(2, action_);
    }
    if (java.lang.Double.doubleToRawLongBits(reward_) != 0) {
      output.writeDouble(3, reward_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idempotencyKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, idempotencyKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getState());
    }
    if (action_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, action_);
    }
    if (java.lang.Double.doubleToRawLongBits(reward_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, reward_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(idempotencyKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, idempotencyKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.optimizer.v1.RewardRequest)) {
      return super.equals(obj);
    }
    database.kernel.grpc.optimizer.v1.RewardRequest other = (database.kernel.grpc.optimizer.v1.RewardRequest) obj;

    if (hasState() != other.hasState()) return false;
    if (hasState()) {
      if (!getState()
          .equals(other.getState())) return false;
    }
    if (getAction()
        != other.getAction()) return false;
    if (java.lang.Double.doubleToLongBits(getReward())
        != java.lang.Double.doubleToLongBits(
            other.getReward())) return false;
    if (!getIdempotencyKey()
        .equals(other.getIdempotencyKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasState()) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
    }
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction();
    hash = (37 * hash) + REWARD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getReward()));
    hash = (37 * hash) + IDEMPOTENCY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getIdempotencyKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.optimizer.v1.RewardRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.optimizer.v1.RewardRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.optimizer.v1.RewardRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.optimizer.v1.RewardRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.optimizer.v1.RewardRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.optimizer.v1.RewardRequest)
      database.kernel.grpc.optimizer.v1.RewardRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.optimizer.v1.RewardRequest.class, database.kernel.grpc.optimizer.v1.RewardRequest.Builder.class);
    }

    // Construct using database.kernel.grpc.optimizer.v1.RewardRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getStateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      state_ = null;
      if (stateBuilder_ != null) {
        stateBuilder_.dispose();
        stateBuilder_ = null;
      }
      action_ = 0;
      reward_ = 0D;
      idempotencyKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardRequest_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.RewardRequest getDefaultInstanceForType() {
      return database.kernel.grpc.optimizer.v1.RewardRequest.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.RewardRequest build() {
      database.kernel.grpc.optimizer.v1.RewardRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.RewardRequest buildPartial() {
      database.kernel.grpc.optimizer.v1.RewardRequest result = new database.kernel.grpc.optimizer.v1.RewardRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(database.kernel.grpc.optimizer.v1.RewardRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.state_ = stateBuilder_ == null
            ? state_
            : stateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.action_ = action_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.reward_ = reward_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.idempotencyKey_ = idempotencyKey_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.optimizer.v1.RewardRequest) {
        return mergeFrom((database.kernel.grpc.optimizer.v1.RewardRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.optimizer.v1.RewardRequest other) {
      if (other == database.kernel.grpc.optimizer.v1.RewardRequest.getDefaultInstance()) return this;
      if (other.hasState()) {
        mergeState(other.getState());
      }
      if (other.getAction() != 0) {
        setAction(other.getAction());
      }
      if (other.getReward() != 0D) {
        setReward(other.getReward());
      }
      if (!other.getIdempotencyKey().isEmpty()) {
        idempotencyKey_ = other.idempotencyKey_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              action_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 25: {
              reward_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              idempotencyKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private database.kernel.grpc.optimizer.v1.QueryState state_;
    private com.google.protobuf.SingleFieldBuilder<
        database.kernel.grpc.optimizer.v1.QueryState, database.kernel.grpc.optimizer.v1.QueryState.Builder, database.kernel.grpc.optimizer.v1.QueryStateOrBuilder> stateBuilder_;
    /**
     * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
     * @return Whether the state field is set.
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
     * @return The state.
     */
    public database.kernel.grpc.optimizer.v1.QueryState getState() {
      if (stateBuilder_ == null) {
        return state_ == null ? database.kernel.grpc.optimizer.v1.QueryState.getDefaultInstance() : state_;
      } else {
        return stateBuilder_.getMessage();
      }
    }
    /**
     * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
     */
    public Builder setState(database.kernel.grpc.optimizer.v1.QueryState value) {
      if (stateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        state_ = value;
      } else {
        stateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
     */
    public Builder setState(
        database.kernel.grpc.optimizer.v1.QueryState.Builder builderForValue) {
      if (stateBuilder_ == null) {
        state_ = builderForValue.build();
      } else {
        stateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
     */
    public Builder mergeState(database.kernel.grpc.optimizer.v1.QueryState value) {
      if (stateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          state_ != null &&
          state_ != database.kernel.grpc.optimizer.v1.QueryState.getDefaultInstance()) {
          getStateBuilder().mergeFrom(value);
        } else {
          state_ = value;
        }
      } else {
        stateBuilder_.mergeFrom(value);
      }
      if (state_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000001);
      state_ = null;
      if (stateBuilder_ != null) {
        stateBuilder_.dispose();
        stateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
     */
    public database.kernel.grpc.optimizer.v1.QueryState.Builder getStateBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getStateFieldBuilder().getBuilder();
    }
    /**
     * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
     */
    public database.kernel.grpc.optimizer.v1.QueryStateOrBuilder getStateOrBuilder() {
      if (stateBuilder_ != null) {
        return stateBuilder_.getMessageOrBuilder();
      } else {
        return state_ == null ?
            database.kernel.grpc.optimizer.v1.QueryState.getDefaultInstance() : state_;
      }
    }
    /**
     * <code>.minipostgres.optimizer.v1.QueryState state = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        database.kernel.grpc.optimizer.v1.QueryState, database.kernel.grpc.optimizer.v1.QueryState.Builder, database.kernel.grpc.optimizer.v1.QueryStateOrBuilder> 
        getStateFieldBuilder() {
      if (stateBuilder_ == null) {
        stateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            database.kernel.grpc.optimizer.v1.QueryState, database.kernel.grpc.optimizer.v1.QueryState.Builder, database.kernel.grpc.optimizer.v1.QueryStateOrBuilder>(
                getState(),
                getParentForChildren(),
                isClean());
        state_ = null;
      }
      return stateBuilder_;
    }

    private int action_ ;
    /**
     * <pre>
     * 0=SeqScan, 1=IndexScan
     * </pre>
     *
     * <code>int32 action = 2;</code>
     * @return The action.
     */
    @java.lang.Override
    public int getAction() {
      return action_;
    }
    /**
     * <pre>
     * 0=SeqScan, 1=IndexScan
     * </pre>
     *
     * <code>int32 action = 2;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(int value) {

      action_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0=SeqScan, 1=IndexScan
     * </pre>
     *
     * <code>int32 action = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000002);
      action_ = 0;
      onChanged();
      return this;
    }

    private double reward_ ;
    /**
     * <pre>
     * Negative execution time in ms
     * </pre>
     *
     * <code>double reward = 3;</code>
     * @return The reward.
     */
    @java.lang.Override
    public double getReward() {
      return reward_;
    }
    /**
     * <pre>
     * Negative execution time in ms
     * </pre>
     *
     * <code>double reward = 3;</code>
     * @param value The reward to set.
     * @return This builder for chaining.
     */
    public Builder setReward(double value) {

      reward_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Negative execution time in ms
     * </pre>
     *
     * <code>double reward = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReward() {
      bitField0_ = (bitField0_ & ~0x00000004);
      reward_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object idempotencyKey_ = "";
    /**
     * <pre>
     * Idempotency key for safe retries
     * </pre>
     *
     * <code>string idempotency_key = 4;</code>
     * @return The idempotencyKey.
     */
    public java.lang.String getIdempotencyKey() {
      java.lang.Object ref = idempotencyKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idempotencyKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Idempotency key for safe retries
     * </pre>
     *
     * <code>string idempotency_key = 4;</code>
     * @return The bytes for idempotencyKey.
     */
    public com.google.protobuf.ByteString
        getIdempotencyKeyBytes() {
      java.lang.Object ref = idempotencyKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idempotencyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Idempotency key for safe retries
     * </pre>
     *
     * <code>string idempotency_key = 4;</code>
     * @param value The idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idempotencyKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Idempotency key for safe retries
     * </pre>
     *
     * <code>string idempotency_key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdempotencyKey() {
      idempotencyKey_ = getDefaultInstance().getIdempotencyKey();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Idempotency key for safe retries
     * </pre>
     *
     * <code>string idempotency_key = 4;</code>
     * @param value The bytes for idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idempotencyKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.optimizer.v1.RewardRequest)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.optimizer.v1.RewardRequest)
  private static final database.kernel.grpc.optimizer.v1.RewardRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.optimizer.v1.RewardRequest();
  }

  public static database.kernel.grpc.optimizer.v1.RewardRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RewardRequest>
      PARSER = new com.google.protobuf.AbstractParser<RewardRequest>() {
    @java.lang.Override
    public RewardRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RewardRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RewardRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.optimizer.v1.RewardRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

