// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

/**
 * Protobuf type {@code minipostgres.optimizer.v1.RewardResponse}
 */
public final class RewardResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.optimizer.v1.RewardResponse)
    RewardResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RewardResponse.class.getName());
  }
  // Use RewardResponse.newBuilder() to construct.
  private RewardResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RewardResponse() {
    status_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.optimizer.v1.RewardResponse.class, database.kernel.grpc.optimizer.v1.RewardResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OLD_VALUE_FIELD_NUMBER = 2;
  private double oldValue_ = 0D;
  /**
   * <code>double old_value = 2;</code>
   * @return The oldValue.
   */
  @java.lang.Override
  public double getOldValue() {
    return oldValue_;
  }

  public static final int NEW_VALUE_FIELD_NUMBER = 3;
  private double newValue_ = 0D;
  /**
   * <code>double new_value = 3;</code>
   * @return The newValue.
   */
  @java.lang.Override
  public double getNewValue() {
    return newValue_;
  }

  public static final int NORMALIZED_REWARD_FIELD_NUMBER = 4;
  private double normalizedReward_ = 0D;
  /**
   * <code>double normalized_reward = 4;</code>
   * @return The normalizedReward.
   */
  @java.lang.Override
  public double getNormalizedReward() {
    return normalizedReward_;
  }

  public static final int EPSILON_FIELD_NUMBER = 5;
  private double epsilon_ = 0D;
  /**
   * <code>double epsilon = 5;</code>
   * @return The epsilon.
   */
  @java.lang.Override
  public double getEpsilon() {
    return epsilon_;
  }

  public static final int IDEMPOTENT_FIELD_NUMBER = 6;
  private boolean idempotent_ = false;
  /**
   * <code>bool idempotent = 6;</code>
   * @return The idempotent.
   */
  @java.lang.Override
  public boolean getIdempotent() {
    return idempotent_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, status_);
    }
    if (java.lang.Double.doubleToRawLongBits(oldValue_) != 0) {
      output.writeDouble(2, oldValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(newValue_) != 0) {
      output.writeDouble(3, newValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(normalizedReward_) != 0) {
      output.writeDouble(4, normalizedReward_);
    }
    if (java.lang.Double.doubleToRawLongBits(epsilon_) != 0) {
      output.writeDouble(5, epsilon_);
    }
    if (idempotent_ != false) {
      output.writeBool(6, idempotent_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, status_);
    }
    if (java.lang.Double.doubleToRawLongBits(oldValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, oldValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(newValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, newValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(normalizedReward_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, normalizedReward_);
    }
    if (java.lang.Double.doubleToRawLongBits(epsilon_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, epsilon_);
    }
    if (idempotent_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, idempotent_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.optimizer.v1.RewardResponse)) {
      return super.equals(obj);
    }
    database.kernel.grpc.optimizer.v1.RewardResponse other = (database.kernel.grpc.optimizer.v1.RewardResponse) obj;

    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (java.lang.Double.doubleToLongBits(getOldValue())
        != java.lang.Double.doubleToLongBits(
            other.getOldValue())) return false;
    if (java.lang.Double.doubleToLongBits(getNewValue())
        != java.lang.Double.doubleToLongBits(
            other.getNewValue())) return false;
    if (java.lang.Double.doubleToLongBits(getNormalizedReward())
        != java.lang.Double.doubleToLongBits(
            other.getNormalizedReward())) return false;
    if (java.lang.Double.doubleToLongBits(getEpsilon())
        != java.lang.Double.doubleToLongBits(
            other.getEpsilon())) return false;
    if (getIdempotent()
        != other.getIdempotent()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + OLD_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getOldValue()));
    hash = (37 * hash) + NEW_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNewValue()));
    hash = (37 * hash) + NORMALIZED_REWARD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNormalizedReward()));
    hash = (37 * hash) + EPSILON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEpsilon()));
    hash = (37 * hash) + IDEMPOTENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIdempotent());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.optimizer.v1.RewardResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.optimizer.v1.RewardResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.optimizer.v1.RewardResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.optimizer.v1.RewardResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.optimizer.v1.RewardResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.optimizer.v1.RewardResponse)
      database.kernel.grpc.optimizer.v1.RewardResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.optimizer.v1.RewardResponse.class, database.kernel.grpc.optimizer.v1.RewardResponse.Builder.class);
    }

    // Construct using database.kernel.grpc.optimizer.v1.RewardResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = "";
      oldValue_ = 0D;
      newValue_ = 0D;
      normalizedReward_ = 0D;
      epsilon_ = 0D;
      idempotent_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.optimizer.v1.QueryOptimizerProto.internal_static_minipostgres_optimizer_v1_RewardResponse_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.RewardResponse getDefaultInstanceForType() {
      return database.kernel.grpc.optimizer.v1.RewardResponse.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.RewardResponse build() {
      database.kernel.grpc.optimizer.v1.RewardResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.optimizer.v1.RewardResponse buildPartial() {
      database.kernel.grpc.optimizer.v1.RewardResponse result = new database.kernel.grpc.optimizer.v1.RewardResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(database.kernel.grpc.optimizer.v1.RewardResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.oldValue_ = oldValue_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.newValue_ = newValue_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.normalizedReward_ = normalizedReward_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.epsilon_ = epsilon_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.idempotent_ = idempotent_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.optimizer.v1.RewardResponse) {
        return mergeFrom((database.kernel.grpc.optimizer.v1.RewardResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.optimizer.v1.RewardResponse other) {
      if (other == database.kernel.grpc.optimizer.v1.RewardResponse.getDefaultInstance()) return this;
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getOldValue() != 0D) {
        setOldValue(other.getOldValue());
      }
      if (other.getNewValue() != 0D) {
        setNewValue(other.getNewValue());
      }
      if (other.getNormalizedReward() != 0D) {
        setNormalizedReward(other.getNormalizedReward());
      }
      if (other.getEpsilon() != 0D) {
        setEpsilon(other.getEpsilon());
      }
      if (other.getIdempotent() != false) {
        setIdempotent(other.getIdempotent());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              oldValue_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              newValue_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              normalizedReward_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              epsilon_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 48: {
              idempotent_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 1;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 1;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double oldValue_ ;
    /**
     * <code>double old_value = 2;</code>
     * @return The oldValue.
     */
    @java.lang.Override
    public double getOldValue() {
      return oldValue_;
    }
    /**
     * <code>double old_value = 2;</code>
     * @param value The oldValue to set.
     * @return This builder for chaining.
     */
    public Builder setOldValue(double value) {

      oldValue_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double old_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOldValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      oldValue_ = 0D;
      onChanged();
      return this;
    }

    private double newValue_ ;
    /**
     * <code>double new_value = 3;</code>
     * @return The newValue.
     */
    @java.lang.Override
    public double getNewValue() {
      return newValue_;
    }
    /**
     * <code>double new_value = 3;</code>
     * @param value The newValue to set.
     * @return This builder for chaining.
     */
    public Builder setNewValue(double value) {

      newValue_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double new_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewValue() {
      bitField0_ = (bitField0_ & ~0x00000004);
      newValue_ = 0D;
      onChanged();
      return this;
    }

    private double normalizedReward_ ;
    /**
     * <code>double normalized_reward = 4;</code>
     * @return The normalizedReward.
     */
    @java.lang.Override
    public double getNormalizedReward() {
      return normalizedReward_;
    }
    /**
     * <code>double normalized_reward = 4;</code>
     * @param value The normalizedReward to set.
     * @return This builder for chaining.
     */
    public Builder setNormalizedReward(double value) {

      normalizedReward_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double normalized_reward = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNormalizedReward() {
      bitField0_ = (bitField0_ & ~0x00000008);
      normalizedReward_ = 0D;
      onChanged();
      return this;
    }

    private double epsilon_ ;
    /**
     * <code>double epsilon = 5;</code>
     * @return The epsilon.
     */
    @java.lang.Override
    public double getEpsilon() {
      return epsilon_;
    }
    /**
     * <code>double epsilon = 5;</code>
     * @param value The epsilon to set.
     * @return This builder for chaining.
     */
    public Builder setEpsilon(double value) {

      epsilon_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double epsilon = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpsilon() {
      bitField0_ = (bitField0_ & ~0x00000010);
      epsilon_ = 0D;
      onChanged();
      return this;
    }

    private boolean idempotent_ ;
    /**
     * <code>bool idempotent = 6;</code>
     * @return The idempotent.
     */
    @java.lang.Override
    public boolean getIdempotent() {
      return idempotent_;
    }
    /**
     * <code>bool idempotent = 6;</code>
     * @param value The idempotent to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotent(boolean value) {

      idempotent_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool idempotent = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdempotent() {
      bitField0_ = (bitField0_ & ~0x00000020);
      idempotent_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.optimizer.v1.RewardResponse)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.optimizer.v1.RewardResponse)
  private static final database.kernel.grpc.optimizer.v1.RewardResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.optimizer.v1.RewardResponse();
  }

  public static database.kernel.grpc.optimizer.v1.RewardResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RewardResponse>
      PARSER = new com.google.protobuf.AbstractParser<RewardResponse>() {
    @java.lang.Override
    public RewardResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RewardResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RewardResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.optimizer.v1.RewardResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

