// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_optimizer.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.optimizer.v1;

public interface RewardResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.optimizer.v1.RewardResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>double old_value = 2;</code>
   * @return The oldValue.
   */
  double getOldValue();

  /**
   * <code>double new_value = 3;</code>
   * @return The newValue.
   */
  double getNewValue();

  /**
   * <code>double normalized_reward = 4;</code>
   * @return The normalizedReward.
   */
  double getNormalizedReward();

  /**
   * <code>double epsilon = 5;</code>
   * @return The epsilon.
   */
  double getEpsilon();

  /**
   * <code>bool idempotent = 6;</code>
   * @return The idempotent.
   */
  boolean getIdempotent();
}
