"""
MiniPostgres RL Optimizer — gRPC Server

Runs alongside the FastAPI HTTP server. Provides high-performance
gRPC endpoints for predict and reward operations from the Java kernel.

Port: 50051 (configurable via RL_GRPC_PORT)
"""

import logging
import uuid
from concurrent import futures

import grpc

# Generated protobuf stubs (generated by grpcio-tools)
import query_optimizer_pb2 as pb2
import query_optimizer_pb2_grpc as pb2_grpc

logger = logging.getLogger("rl_optimizer.grpc")


class QueryOptimizerServicer(pb2_grpc.QueryOptimizerServiceServicer):
    """gRPC servicer that delegates to the same RL Agent used by FastAPI."""

    def __init__(self, agent, q_store, exp_store, idempotency_cache):
        self.agent = agent
        self.q_store = q_store
        self.exp_store = exp_store
        self.idempotency_cache = idempotency_cache
        logger.info("QueryOptimizerServicer initialized")

    def Predict(self, request, context):
        """Predict the best scan action for a query state."""
        from agent import RLAgent

        if self.agent is None:
            context.set_code(grpc.StatusCode.UNAVAILABLE)
            context.set_details("Service not ready")
            return pb2.PredictResponse()

        state_key, *_ = RLAgent.encode_state(
            num_rows=request.num_rows,
            is_range=request.is_range,
            has_index=request.has_index,
            predicate_type=request.predicate_type,
            estimated_matches=request.estimated_matches,
        )

        action = self.agent.predict(
            state_key,
            has_index=request.has_index,
            is_range=request.is_range,
        )

        return pb2.PredictResponse(
            action=action,
            state_key=state_key,
        )

    def ReportReward(self, request, context):
        """Report execution reward for RL learning (idempotent)."""
        from agent import RLAgent

        if self.agent is None:
            context.set_code(grpc.StatusCode.UNAVAILABLE)
            context.set_details("Service not ready")
            return pb2.RewardResponse()

        # Idempotency check
        idempotency_key = request.idempotency_key
        if idempotency_key:
            cached = self.idempotency_cache.get(idempotency_key)
            if cached is not None:
                logger.info("Idempotent replay for gRPC request %s", idempotency_key)
                return pb2.RewardResponse(
                    status="ok",
                    idempotent=True,
                    old_value=cached.get("old_value", 0.0),
                    new_value=cached.get("new_value", 0.0),
                    normalized_reward=cached.get("normalized_reward", 0.0),
                    epsilon=cached.get("epsilon", 0.0),
                )

        # Encode state
        state = request.state
        state_key, size_bucket, selectivity, has_index, pred_type, card = RLAgent.encode_state(
            num_rows=state.num_rows,
            is_range=state.is_range,
            has_index=state.has_index,
            predicate_type=state.predicate_type,
            estimated_matches=state.estimated_matches,
        )

        raw_time_ms = abs(request.reward)

        # Update the agent
        result = self.agent.update(
            state_key=state_key,
            size_bucket=size_bucket,
            selectivity=selectivity,
            has_index=has_index,
            predicate_type=pred_type,
            cardinality_bucket=card,
            action=request.action,
            raw_time_ms=raw_time_ms,
            num_rows=state.num_rows,
        )

        # Cache for idempotency
        if idempotency_key:
            self.idempotency_cache.put(idempotency_key, result)

        return pb2.RewardResponse(
            status="ok",
            old_value=result.get("old_value", 0.0),
            new_value=result.get("new_value", 0.0),
            normalized_reward=result.get("normalized_reward", 0.0),
            epsilon=result.get("epsilon", 0.0),
            idempotent=False,
        )

    def HealthCheck(self, request, context):
        """Health check for the optimizer service."""
        ready = self.agent is not None
        return pb2.HealthCheckResponse(
            status="healthy" if ready else "starting",
            ready=ready,
            q_table_states=self.q_store.state_count() if ready else 0,
            experience_count=self.exp_store.size() if ready else 0,
            version="2.0.0",
        )


def start_grpc_server(agent, q_store, exp_store, idempotency_cache, port=50051):
    """Start the gRPC server in a background thread."""
    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=10),
        options=[
            ("grpc.max_send_message_length", 4 * 1024 * 1024),
            ("grpc.max_receive_message_length", 4 * 1024 * 1024),
            ("grpc.keepalive_time_ms", 30000),
            ("grpc.keepalive_timeout_ms", 5000),
            ("grpc.keepalive_permit_without_calls", True),
        ],
    )

    servicer = QueryOptimizerServicer(agent, q_store, exp_store, idempotency_cache)
    pb2_grpc.add_QueryOptimizerServiceServicer_to_server(servicer, server)

    server.add_insecure_port(f"[::]:{port}")
    server.start()
    logger.info("gRPC server started on port %d", port)

    return server
