# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query_optimizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'query_optimizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15query_optimizer.proto\x12\x19minipostgres.optimizer.v1\"\x8e\x01\n\x0ePredictRequest\x12\x10\n\x08num_rows\x18\x01 \x01(\x05\x12\x10\n\x08is_range\x18\x02 \x01(\x08\x12\x11\n\thas_index\x18\x03 \x01(\x08\x12\x16\n\x0epredicate_type\x18\x04 \x01(\x05\x12\x19\n\x11\x65stimated_matches\x18\x05 \x01(\x05\x12\x12\n\nrequest_id\x18\x06 \x01(\t\"4\n\x0fPredictResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x12\x11\n\tstate_key\x18\x02 \x01(\t\"~\n\rRewardRequest\x12\x34\n\x05state\x18\x01 \x01(\x0b\x32%.minipostgres.optimizer.v1.QueryState\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\x12\x0e\n\x06reward\x18\x03 \x01(\x01\x12\x17\n\x0fidempotency_key\x18\x04 \x01(\t\"v\n\nQueryState\x12\x10\n\x08num_rows\x18\x01 \x01(\x05\x12\x10\n\x08is_range\x18\x02 \x01(\x08\x12\x11\n\thas_index\x18\x03 \x01(\x08\x12\x16\n\x0epredicate_type\x18\x04 \x01(\x05\x12\x19\n\x11\x65stimated_matches\x18\x05 \x01(\x05\"\x86\x01\n\x0eRewardResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\told_value\x18\x02 \x01(\x01\x12\x11\n\tnew_value\x18\x03 \x01(\x01\x12\x19\n\x11normalized_reward\x18\x04 \x01(\x01\x12\x0f\n\x07\x65psilon\x18\x05 \x01(\x01\x12\x12\n\nidempotent\x18\x06 \x01(\x08\"\x14\n\x12HealthCheckRequest\"w\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05ready\x18\x02 \x01(\x08\x12\x16\n\x0eq_table_states\x18\x03 \x01(\x05\x12\x18\n\x10\x65xperience_count\x18\x04 \x01(\x05\x12\x0f\n\x07version\x18\x05 \x01(\t2\xcc\x02\n\x15QueryOptimizerService\x12`\n\x07Predict\x12).minipostgres.optimizer.v1.PredictRequest\x1a*.minipostgres.optimizer.v1.PredictResponse\x12\x63\n\x0cReportReward\x12(.minipostgres.optimizer.v1.RewardRequest\x1a).minipostgres.optimizer.v1.RewardResponse\x12l\n\x0bHealthCheck\x12-.minipostgres.optimizer.v1.HealthCheckRequest\x1a..minipostgres.optimizer.v1.HealthCheckResponseB:\n!database.kernel.grpc.optimizer.v1B\x13QueryOptimizerProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_optimizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!database.kernel.grpc.optimizer.v1B\023QueryOptimizerProtoP\001'
  _globals['_PREDICTREQUEST']._serialized_start=53
  _globals['_PREDICTREQUEST']._serialized_end=195
  _globals['_PREDICTRESPONSE']._serialized_start=197
  _globals['_PREDICTRESPONSE']._serialized_end=249
  _globals['_REWARDREQUEST']._serialized_start=251
  _globals['_REWARDREQUEST']._serialized_end=377
  _globals['_QUERYSTATE']._serialized_start=379
  _globals['_QUERYSTATE']._serialized_end=497
  _globals['_REWARDRESPONSE']._serialized_start=500
  _globals['_REWARDRESPONSE']._serialized_end=634
  _globals['_HEALTHCHECKREQUEST']._serialized_start=636
  _globals['_HEALTHCHECKREQUEST']._serialized_end=656
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=658
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=777
  _globals['_QUERYOPTIMIZERSERVICE']._serialized_start=780
  _globals['_QUERYOPTIMIZERSERVICE']._serialized_end=1112
# @@protoc_insertion_point(module_scope)
