// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public interface CommandResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.query.v1.CommandResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The original SQL command
   * </pre>
   *
   * <code>string sql = 1;</code>
   * @return The sql.
   */
  java.lang.String getSql();
  /**
   * <pre>
   * The original SQL command
   * </pre>
   *
   * <code>string sql = 1;</code>
   * @return The bytes for sql.
   */
  com.google.protobuf.ByteString
      getSqlBytes();

  /**
   * <pre>
   * Human-readable output (REPL-style)
   * </pre>
   *
   * <code>string output = 2;</code>
   * @return The output.
   */
  java.lang.String getOutput();
  /**
   * <pre>
   * Human-readable output (REPL-style)
   * </pre>
   *
   * <code>string output = 2;</code>
   * @return The bytes for output.
   */
  com.google.protobuf.ByteString
      getOutputBytes();

  /**
   * <pre>
   * Structured result set (for SELECTs)
   * </pre>
   *
   * <code>.minipostgres.query.v1.ResultSet result_set = 3;</code>
   * @return Whether the resultSet field is set.
   */
  boolean hasResultSet();
  /**
   * <pre>
   * Structured result set (for SELECTs)
   * </pre>
   *
   * <code>.minipostgres.query.v1.ResultSet result_set = 3;</code>
   * @return The resultSet.
   */
  database.kernel.grpc.query.v1.ResultSet getResultSet();
  /**
   * <pre>
   * Structured result set (for SELECTs)
   * </pre>
   *
   * <code>.minipostgres.query.v1.ResultSet result_set = 3;</code>
   */
  database.kernel.grpc.query.v1.ResultSetOrBuilder getResultSetOrBuilder();

  /**
   * <pre>
   * true if SELECT, false if DDL/DML
   * </pre>
   *
   * <code>bool is_query = 4;</code>
   * @return The isQuery.
   */
  boolean getIsQuery();

  /**
   * <pre>
   * Execution strategy used (SeqScan, IndexScan)
   * </pre>
   *
   * <code>string strategy = 5;</code>
   * @return The strategy.
   */
  java.lang.String getStrategy();
  /**
   * <pre>
   * Execution strategy used (SeqScan, IndexScan)
   * </pre>
   *
   * <code>string strategy = 5;</code>
   * @return The bytes for strategy.
   */
  com.google.protobuf.ByteString
      getStrategyBytes();

  /**
   * <pre>
   * Execution time in nanoseconds
   * </pre>
   *
   * <code>int64 elapsed_nanos = 6;</code>
   * @return The elapsedNanos.
   */
  long getElapsedNanos();
}
