// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public interface ExecuteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.query.v1.ExecuteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <pre>
   * Error message if ok=false
   * </pre>
   *
   * <code>string error = 2;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <pre>
   * Error message if ok=false
   * </pre>
   *
   * <code>string error = 2;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  java.util.List<database.kernel.grpc.query.v1.CommandResult> 
      getResultsList();
  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  database.kernel.grpc.query.v1.CommandResult getResults(int index);
  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  int getResultsCount();
  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  java.util.List<? extends database.kernel.grpc.query.v1.CommandResultOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  database.kernel.grpc.query.v1.CommandResultOrBuilder getResultsOrBuilder(
      int index);

  /**
   * <code>int32 command_count = 4;</code>
   * @return The commandCount.
   */
  int getCommandCount();

  /**
   * <code>int64 total_elapsed_nanos = 5;</code>
   * @return The totalElapsedNanos.
   */
  long getTotalElapsedNanos();
}
