// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public interface ExecuteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.query.v1.ExecuteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Raw SQL string (may contain multiple statements)
   * </pre>
   *
   * <code>string sql = 1;</code>
   * @return The sql.
   */
  java.lang.String getSql();
  /**
   * <pre>
   * Raw SQL string (may contain multiple statements)
   * </pre>
   *
   * <code>string sql = 1;</code>
   * @return The bytes for sql.
   */
  com.google.protobuf.ByteString
      getSqlBytes();

  /**
   * <pre>
   * Correlation/tracing ID
   * </pre>
   *
   * <code>string request_id = 2;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * Correlation/tracing ID
   * </pre>
   *
   * <code>string request_id = 2;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * Max rows to return (0 = unlimited)
   * </pre>
   *
   * <code>int32 max_rows = 3;</code>
   * @return The maxRows.
   */
  int getMaxRows();
}
