// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

/**
 * Protobuf type {@code minipostgres.query.v1.ExecuteResponse}
 */
public final class ExecuteResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.query.v1.ExecuteResponse)
    ExecuteResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ExecuteResponse.class.getName());
  }
  // Use ExecuteResponse.newBuilder() to construct.
  private ExecuteResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExecuteResponse() {
    error_ = "";
    results_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ExecuteResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ExecuteResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.query.v1.ExecuteResponse.class, database.kernel.grpc.query.v1.ExecuteResponse.Builder.class);
  }

  public static final int OK_FIELD_NUMBER = 1;
  private boolean ok_ = false;
  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  @java.lang.Override
  public boolean getOk() {
    return ok_;
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <pre>
   * Error message if ok=false
   * </pre>
   *
   * <code>string error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Error message if ok=false
   * </pre>
   *
   * <code>string error = 2;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULTS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<database.kernel.grpc.query.v1.CommandResult> results_;
  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  @java.lang.Override
  public java.util.List<database.kernel.grpc.query.v1.CommandResult> getResultsList() {
    return results_;
  }
  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends database.kernel.grpc.query.v1.CommandResultOrBuilder> 
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  @java.lang.Override
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.CommandResult getResults(int index) {
    return results_.get(index);
  }
  /**
   * <pre>
   * One result per SQL statement
   * </pre>
   *
   * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.CommandResultOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  public static final int COMMAND_COUNT_FIELD_NUMBER = 4;
  private int commandCount_ = 0;
  /**
   * <code>int32 command_count = 4;</code>
   * @return The commandCount.
   */
  @java.lang.Override
  public int getCommandCount() {
    return commandCount_;
  }

  public static final int TOTAL_ELAPSED_NANOS_FIELD_NUMBER = 5;
  private long totalElapsedNanos_ = 0L;
  /**
   * <code>int64 total_elapsed_nanos = 5;</code>
   * @return The totalElapsedNanos.
   */
  @java.lang.Override
  public long getTotalElapsedNanos() {
    return totalElapsedNanos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ok_ != false) {
      output.writeBool(1, ok_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, error_);
    }
    for (int i = 0; i < results_.size(); i++) {
      output.writeMessage(3, results_.get(i));
    }
    if (commandCount_ != 0) {
      output.writeInt32(4, commandCount_);
    }
    if (totalElapsedNanos_ != 0L) {
      output.writeInt64(5, totalElapsedNanos_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ok_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, ok_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, error_);
    }
    for (int i = 0; i < results_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, results_.get(i));
    }
    if (commandCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, commandCount_);
    }
    if (totalElapsedNanos_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, totalElapsedNanos_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.query.v1.ExecuteResponse)) {
      return super.equals(obj);
    }
    database.kernel.grpc.query.v1.ExecuteResponse other = (database.kernel.grpc.query.v1.ExecuteResponse) obj;

    if (getOk()
        != other.getOk()) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getResultsList()
        .equals(other.getResultsList())) return false;
    if (getCommandCount()
        != other.getCommandCount()) return false;
    if (getTotalElapsedNanos()
        != other.getTotalElapsedNanos()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOk());
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    hash = (37 * hash) + COMMAND_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCommandCount();
    hash = (37 * hash) + TOTAL_ELAPSED_NANOS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalElapsedNanos());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.query.v1.ExecuteResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.query.v1.ExecuteResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.query.v1.ExecuteResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.query.v1.ExecuteResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.query.v1.ExecuteResponse)
      database.kernel.grpc.query.v1.ExecuteResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ExecuteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.query.v1.ExecuteResponse.class, database.kernel.grpc.query.v1.ExecuteResponse.Builder.class);
    }

    // Construct using database.kernel.grpc.query.v1.ExecuteResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ok_ = false;
      error_ = "";
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
      } else {
        results_ = null;
        resultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      commandCount_ = 0;
      totalElapsedNanos_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.ExecuteResponse getDefaultInstanceForType() {
      return database.kernel.grpc.query.v1.ExecuteResponse.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.ExecuteResponse build() {
      database.kernel.grpc.query.v1.ExecuteResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.ExecuteResponse buildPartial() {
      database.kernel.grpc.query.v1.ExecuteResponse result = new database.kernel.grpc.query.v1.ExecuteResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(database.kernel.grpc.query.v1.ExecuteResponse result) {
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
    }

    private void buildPartial0(database.kernel.grpc.query.v1.ExecuteResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ok_ = ok_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.error_ = error_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.commandCount_ = commandCount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.totalElapsedNanos_ = totalElapsedNanos_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.query.v1.ExecuteResponse) {
        return mergeFrom((database.kernel.grpc.query.v1.ExecuteResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.query.v1.ExecuteResponse other) {
      if (other == database.kernel.grpc.query.v1.ExecuteResponse.getDefaultInstance()) return this;
      if (other.getOk() != false) {
        setOk(other.getOk());
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (resultsBuilder_ == null) {
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
      } else {
        if (!other.results_.isEmpty()) {
          if (resultsBuilder_.isEmpty()) {
            resultsBuilder_.dispose();
            resultsBuilder_ = null;
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000004);
            resultsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getResultsFieldBuilder() : null;
          } else {
            resultsBuilder_.addAllMessages(other.results_);
          }
        }
      }
      if (other.getCommandCount() != 0) {
        setCommandCount(other.getCommandCount());
      }
      if (other.getTotalElapsedNanos() != 0L) {
        setTotalElapsedNanos(other.getTotalElapsedNanos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ok_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              database.kernel.grpc.query.v1.CommandResult m =
                  input.readMessage(
                      database.kernel.grpc.query.v1.CommandResult.parser(),
                      extensionRegistry);
              if (resultsBuilder_ == null) {
                ensureResultsIsMutable();
                results_.add(m);
              } else {
                resultsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              commandCount_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              totalElapsedNanos_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean ok_ ;
    /**
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return ok_;
    }
    /**
     * <code>bool ok = 1;</code>
     * @param value The ok to set.
     * @return This builder for chaining.
     */
    public Builder setOk(boolean value) {

      ok_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool ok = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOk() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ok_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <pre>
     * Error message if ok=false
     * </pre>
     *
     * <code>string error = 2;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Error message if ok=false
     * </pre>
     *
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Error message if ok=false
     * </pre>
     *
     * <code>string error = 2;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error message if ok=false
     * </pre>
     *
     * <code>string error = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error message if ok=false
     * </pre>
     *
     * <code>string error = 2;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<database.kernel.grpc.query.v1.CommandResult> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        results_ = new java.util.ArrayList<database.kernel.grpc.query.v1.CommandResult>(results_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.CommandResult, database.kernel.grpc.query.v1.CommandResult.Builder, database.kernel.grpc.query.v1.CommandResultOrBuilder> resultsBuilder_;

    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.CommandResult> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public database.kernel.grpc.query.v1.CommandResult getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public Builder setResults(
        int index, database.kernel.grpc.query.v1.CommandResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public Builder setResults(
        int index, database.kernel.grpc.query.v1.CommandResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public Builder addResults(database.kernel.grpc.query.v1.CommandResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public Builder addResults(
        int index, database.kernel.grpc.query.v1.CommandResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public Builder addResults(
        database.kernel.grpc.query.v1.CommandResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public Builder addResults(
        int index, database.kernel.grpc.query.v1.CommandResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends database.kernel.grpc.query.v1.CommandResult> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public database.kernel.grpc.query.v1.CommandResult.Builder getResultsBuilder(
        int index) {
      return getResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public database.kernel.grpc.query.v1.CommandResultOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public java.util.List<? extends database.kernel.grpc.query.v1.CommandResultOrBuilder> 
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public database.kernel.grpc.query.v1.CommandResult.Builder addResultsBuilder() {
      return getResultsFieldBuilder().addBuilder(
          database.kernel.grpc.query.v1.CommandResult.getDefaultInstance());
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public database.kernel.grpc.query.v1.CommandResult.Builder addResultsBuilder(
        int index) {
      return getResultsFieldBuilder().addBuilder(
          index, database.kernel.grpc.query.v1.CommandResult.getDefaultInstance());
    }
    /**
     * <pre>
     * One result per SQL statement
     * </pre>
     *
     * <code>repeated .minipostgres.query.v1.CommandResult results = 3;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.CommandResult.Builder> 
         getResultsBuilderList() {
      return getResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.CommandResult, database.kernel.grpc.query.v1.CommandResult.Builder, database.kernel.grpc.query.v1.CommandResultOrBuilder> 
        getResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            database.kernel.grpc.query.v1.CommandResult, database.kernel.grpc.query.v1.CommandResult.Builder, database.kernel.grpc.query.v1.CommandResultOrBuilder>(
                results_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }

    private int commandCount_ ;
    /**
     * <code>int32 command_count = 4;</code>
     * @return The commandCount.
     */
    @java.lang.Override
    public int getCommandCount() {
      return commandCount_;
    }
    /**
     * <code>int32 command_count = 4;</code>
     * @param value The commandCount to set.
     * @return This builder for chaining.
     */
    public Builder setCommandCount(int value) {

      commandCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 command_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      commandCount_ = 0;
      onChanged();
      return this;
    }

    private long totalElapsedNanos_ ;
    /**
     * <code>int64 total_elapsed_nanos = 5;</code>
     * @return The totalElapsedNanos.
     */
    @java.lang.Override
    public long getTotalElapsedNanos() {
      return totalElapsedNanos_;
    }
    /**
     * <code>int64 total_elapsed_nanos = 5;</code>
     * @param value The totalElapsedNanos to set.
     * @return This builder for chaining.
     */
    public Builder setTotalElapsedNanos(long value) {

      totalElapsedNanos_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_elapsed_nanos = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalElapsedNanos() {
      bitField0_ = (bitField0_ & ~0x00000010);
      totalElapsedNanos_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.query.v1.ExecuteResponse)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.query.v1.ExecuteResponse)
  private static final database.kernel.grpc.query.v1.ExecuteResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.query.v1.ExecuteResponse();
  }

  public static database.kernel.grpc.query.v1.ExecuteResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteResponse>() {
    @java.lang.Override
    public ExecuteResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.query.v1.ExecuteResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

