// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public interface QueryResultRowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.query.v1.QueryResultRow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.minipostgres.query.v1.Row row = 1;</code>
   * @return Whether the row field is set.
   */
  boolean hasRow();
  /**
   * <code>.minipostgres.query.v1.Row row = 1;</code>
   * @return The row.
   */
  database.kernel.grpc.query.v1.Row getRow();
  /**
   * <code>.minipostgres.query.v1.Row row = 1;</code>
   */
  database.kernel.grpc.query.v1.RowOrBuilder getRowOrBuilder();

  /**
   * <pre>
   * True for the final message in the stream
   * </pre>
   *
   * <code>bool is_last = 2;</code>
   * @return The isLast.
   */
  boolean getIsLast();

  /**
   * <pre>
   * Only populated on the first row
   * </pre>
   *
   * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
   * @return Whether the meta field is set.
   */
  boolean hasMeta();
  /**
   * <pre>
   * Only populated on the first row
   * </pre>
   *
   * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
   * @return The meta.
   */
  database.kernel.grpc.query.v1.ResultSetMeta getMeta();
  /**
   * <pre>
   * Only populated on the first row
   * </pre>
   *
   * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
   */
  database.kernel.grpc.query.v1.ResultSetMetaOrBuilder getMetaOrBuilder();
}
