// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public final class QueryServiceProto {
  private QueryServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      QueryServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_ExecuteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_ExecuteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_ExecuteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_ExecuteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_CommandResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_CommandResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_ResultSet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_ResultSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_ColumnMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_ColumnMeta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_Row_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_Row_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_StateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_StateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_StateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_StateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_TableInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_TableInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_QueryResultRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_QueryResultRow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minipostgres_query_v1_ResultSetMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minipostgres_query_v1_ResultSetMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023query_service.proto\022\025minipostgres.quer" +
      "y.v1\"C\n\016ExecuteRequest\022\013\n\003sql\030\001 \001(\t\022\022\n\nr" +
      "equest_id\030\002 \001(\t\022\020\n\010max_rows\030\003 \001(\005\"\227\001\n\017Ex" +
      "ecuteResponse\022\n\n\002ok\030\001 \001(\010\022\r\n\005error\030\002 \001(\t" +
      "\0225\n\007results\030\003 \003(\0132$.minipostgres.query.v" +
      "1.CommandResult\022\025\n\rcommand_count\030\004 \001(\005\022\033" +
      "\n\023total_elapsed_nanos\030\005 \001(\003\"\235\001\n\rCommandR" +
      "esult\022\013\n\003sql\030\001 \001(\t\022\016\n\006output\030\002 \001(\t\0224\n\nre" +
      "sult_set\030\003 \001(\0132 .minipostgres.query.v1.R" +
      "esultSet\022\020\n\010is_query\030\004 \001(\010\022\020\n\010strategy\030\005" +
      " \001(\t\022\025\n\relapsed_nanos\030\006 \001(\003\"|\n\tResultSet" +
      "\0222\n\007columns\030\001 \003(\0132!.minipostgres.query.v" +
      "1.ColumnMeta\022(\n\004rows\030\002 \003(\0132\032.minipostgre" +
      "s.query.v1.Row\022\021\n\trow_count\030\003 \001(\005\"6\n\nCol" +
      "umnMeta\022\014\n\004name\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\014\n\004s" +
      "ize\030\003 \001(\005\"3\n\003Row\022,\n\006values\030\001 \003(\0132\034.minip" +
      "ostgres.query.v1.Value\"_\n\005Value\022\021\n\007int_v" +
      "al\030\001 \001(\005H\000\022\023\n\tfloat_val\030\002 \001(\002H\000\022\024\n\nstrin" +
      "g_val\030\003 \001(\tH\000\022\021\n\007is_null\030\004 \001(\010H\000B\005\n\003val\"" +
      "\"\n\014StateRequest\022\022\n\nrequest_id\030\001 \001(\t\"\237\001\n\r" +
      "StateResponse\022\n\n\002ok\030\001 \001(\010\022\026\n\016data_direct" +
      "ory\030\002 \001(\t\022\023\n\013table_count\030\003 \001(\005\0220\n\006tables" +
      "\030\004 \003(\0132 .minipostgres.query.v1.TableInfo" +
      "\022\017\n\007indexes\030\005 \003(\t\022\022\n\ndata_files\030\006 \003(\t\"]\n" +
      "\tTableInfo\022\014\n\004name\030\001 \001(\t\022\016\n\006schema\030\002 \001(\t" +
      "\0222\n\007columns\030\003 \003(\0132!.minipostgres.query.v" +
      "1.ColumnMeta\"~\n\016QueryResultRow\022\'\n\003row\030\001 " +
      "\001(\0132\032.minipostgres.query.v1.Row\022\017\n\007is_la" +
      "st\030\002 \001(\010\0222\n\004meta\030\003 \001(\0132$.minipostgres.qu" +
      "ery.v1.ResultSetMeta\"\200\001\n\rResultSetMeta\0222" +
      "\n\007columns\030\001 \003(\0132!.minipostgres.query.v1." +
      "ColumnMeta\022\020\n\010strategy\030\002 \001(\t\022\025\n\relapsed_" +
      "nanos\030\003 \001(\003\022\022\n\ntotal_rows\030\004 \001(\0052\240\002\n\014Quer" +
      "yService\022X\n\007Execute\022%.minipostgres.query" +
      ".v1.ExecuteRequest\032&.minipostgres.query." +
      "v1.ExecuteResponse\022U\n\010GetState\022#.minipos" +
      "tgres.query.v1.StateRequest\032$.minipostgr" +
      "es.query.v1.StateResponse\022_\n\rExecuteStre" +
      "am\022%.minipostgres.query.v1.ExecuteReques" +
      "t\032%.minipostgres.query.v1.QueryResultRow" +
      "0\001B4\n\035database.kernel.grpc.query.v1B\021Que" +
      "ryServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_minipostgres_query_v1_ExecuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_minipostgres_query_v1_ExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_ExecuteRequest_descriptor,
        new java.lang.String[] { "Sql", "RequestId", "MaxRows", });
    internal_static_minipostgres_query_v1_ExecuteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_minipostgres_query_v1_ExecuteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_ExecuteResponse_descriptor,
        new java.lang.String[] { "Ok", "Error", "Results", "CommandCount", "TotalElapsedNanos", });
    internal_static_minipostgres_query_v1_CommandResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_minipostgres_query_v1_CommandResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_CommandResult_descriptor,
        new java.lang.String[] { "Sql", "Output", "ResultSet", "IsQuery", "Strategy", "ElapsedNanos", });
    internal_static_minipostgres_query_v1_ResultSet_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_minipostgres_query_v1_ResultSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_ResultSet_descriptor,
        new java.lang.String[] { "Columns", "Rows", "RowCount", });
    internal_static_minipostgres_query_v1_ColumnMeta_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_minipostgres_query_v1_ColumnMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_ColumnMeta_descriptor,
        new java.lang.String[] { "Name", "Type", "Size", });
    internal_static_minipostgres_query_v1_Row_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_minipostgres_query_v1_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_Row_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_minipostgres_query_v1_Value_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_minipostgres_query_v1_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_Value_descriptor,
        new java.lang.String[] { "IntVal", "FloatVal", "StringVal", "IsNull", "Val", });
    internal_static_minipostgres_query_v1_StateRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_minipostgres_query_v1_StateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_StateRequest_descriptor,
        new java.lang.String[] { "RequestId", });
    internal_static_minipostgres_query_v1_StateResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_minipostgres_query_v1_StateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_StateResponse_descriptor,
        new java.lang.String[] { "Ok", "DataDirectory", "TableCount", "Tables", "Indexes", "DataFiles", });
    internal_static_minipostgres_query_v1_TableInfo_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_minipostgres_query_v1_TableInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_TableInfo_descriptor,
        new java.lang.String[] { "Name", "Schema", "Columns", });
    internal_static_minipostgres_query_v1_QueryResultRow_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_minipostgres_query_v1_QueryResultRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_QueryResultRow_descriptor,
        new java.lang.String[] { "Row", "IsLast", "Meta", });
    internal_static_minipostgres_query_v1_ResultSetMeta_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_minipostgres_query_v1_ResultSetMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minipostgres_query_v1_ResultSetMeta_descriptor,
        new java.lang.String[] { "Columns", "Strategy", "ElapsedNanos", "TotalRows", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
