// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

/**
 * Protobuf type {@code minipostgres.query.v1.QueryResultRow}
 */
public final class QueryResultRow extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.query.v1.QueryResultRow)
    QueryResultRowOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      QueryResultRow.class.getName());
  }
  // Use QueryResultRow.newBuilder() to construct.
  private QueryResultRow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private QueryResultRow() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_QueryResultRow_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_QueryResultRow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.query.v1.QueryResultRow.class, database.kernel.grpc.query.v1.QueryResultRow.Builder.class);
  }

  private int bitField0_;
  public static final int ROW_FIELD_NUMBER = 1;
  private database.kernel.grpc.query.v1.Row row_;
  /**
   * <code>.minipostgres.query.v1.Row row = 1;</code>
   * @return Whether the row field is set.
   */
  @java.lang.Override
  public boolean hasRow() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.minipostgres.query.v1.Row row = 1;</code>
   * @return The row.
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.Row getRow() {
    return row_ == null ? database.kernel.grpc.query.v1.Row.getDefaultInstance() : row_;
  }
  /**
   * <code>.minipostgres.query.v1.Row row = 1;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.RowOrBuilder getRowOrBuilder() {
    return row_ == null ? database.kernel.grpc.query.v1.Row.getDefaultInstance() : row_;
  }

  public static final int IS_LAST_FIELD_NUMBER = 2;
  private boolean isLast_ = false;
  /**
   * <pre>
   * True for the final message in the stream
   * </pre>
   *
   * <code>bool is_last = 2;</code>
   * @return The isLast.
   */
  @java.lang.Override
  public boolean getIsLast() {
    return isLast_;
  }

  public static final int META_FIELD_NUMBER = 3;
  private database.kernel.grpc.query.v1.ResultSetMeta meta_;
  /**
   * <pre>
   * Only populated on the first row
   * </pre>
   *
   * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
   * @return Whether the meta field is set.
   */
  @java.lang.Override
  public boolean hasMeta() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Only populated on the first row
   * </pre>
   *
   * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
   * @return The meta.
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.ResultSetMeta getMeta() {
    return meta_ == null ? database.kernel.grpc.query.v1.ResultSetMeta.getDefaultInstance() : meta_;
  }
  /**
   * <pre>
   * Only populated on the first row
   * </pre>
   *
   * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.ResultSetMetaOrBuilder getMetaOrBuilder() {
    return meta_ == null ? database.kernel.grpc.query.v1.ResultSetMeta.getDefaultInstance() : meta_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRow());
    }
    if (isLast_ != false) {
      output.writeBool(2, isLast_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getMeta());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRow());
    }
    if (isLast_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isLast_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMeta());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.query.v1.QueryResultRow)) {
      return super.equals(obj);
    }
    database.kernel.grpc.query.v1.QueryResultRow other = (database.kernel.grpc.query.v1.QueryResultRow) obj;

    if (hasRow() != other.hasRow()) return false;
    if (hasRow()) {
      if (!getRow()
          .equals(other.getRow())) return false;
    }
    if (getIsLast()
        != other.getIsLast()) return false;
    if (hasMeta() != other.hasMeta()) return false;
    if (hasMeta()) {
      if (!getMeta()
          .equals(other.getMeta())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRow()) {
      hash = (37 * hash) + ROW_FIELD_NUMBER;
      hash = (53 * hash) + getRow().hashCode();
    }
    hash = (37 * hash) + IS_LAST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLast());
    if (hasMeta()) {
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.query.v1.QueryResultRow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.query.v1.QueryResultRow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.QueryResultRow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.query.v1.QueryResultRow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.query.v1.QueryResultRow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.query.v1.QueryResultRow)
      database.kernel.grpc.query.v1.QueryResultRowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_QueryResultRow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_QueryResultRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.query.v1.QueryResultRow.class, database.kernel.grpc.query.v1.QueryResultRow.Builder.class);
    }

    // Construct using database.kernel.grpc.query.v1.QueryResultRow.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getRowFieldBuilder();
        getMetaFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      row_ = null;
      if (rowBuilder_ != null) {
        rowBuilder_.dispose();
        rowBuilder_ = null;
      }
      isLast_ = false;
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_QueryResultRow_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.QueryResultRow getDefaultInstanceForType() {
      return database.kernel.grpc.query.v1.QueryResultRow.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.QueryResultRow build() {
      database.kernel.grpc.query.v1.QueryResultRow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.QueryResultRow buildPartial() {
      database.kernel.grpc.query.v1.QueryResultRow result = new database.kernel.grpc.query.v1.QueryResultRow(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(database.kernel.grpc.query.v1.QueryResultRow result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.row_ = rowBuilder_ == null
            ? row_
            : rowBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isLast_ = isLast_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.meta_ = metaBuilder_ == null
            ? meta_
            : metaBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.query.v1.QueryResultRow) {
        return mergeFrom((database.kernel.grpc.query.v1.QueryResultRow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.query.v1.QueryResultRow other) {
      if (other == database.kernel.grpc.query.v1.QueryResultRow.getDefaultInstance()) return this;
      if (other.hasRow()) {
        mergeRow(other.getRow());
      }
      if (other.getIsLast() != false) {
        setIsLast(other.getIsLast());
      }
      if (other.hasMeta()) {
        mergeMeta(other.getMeta());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRowFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isLast_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getMetaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private database.kernel.grpc.query.v1.Row row_;
    private com.google.protobuf.SingleFieldBuilder<
        database.kernel.grpc.query.v1.Row, database.kernel.grpc.query.v1.Row.Builder, database.kernel.grpc.query.v1.RowOrBuilder> rowBuilder_;
    /**
     * <code>.minipostgres.query.v1.Row row = 1;</code>
     * @return Whether the row field is set.
     */
    public boolean hasRow() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.minipostgres.query.v1.Row row = 1;</code>
     * @return The row.
     */
    public database.kernel.grpc.query.v1.Row getRow() {
      if (rowBuilder_ == null) {
        return row_ == null ? database.kernel.grpc.query.v1.Row.getDefaultInstance() : row_;
      } else {
        return rowBuilder_.getMessage();
      }
    }
    /**
     * <code>.minipostgres.query.v1.Row row = 1;</code>
     */
    public Builder setRow(database.kernel.grpc.query.v1.Row value) {
      if (rowBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        row_ = value;
      } else {
        rowBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.minipostgres.query.v1.Row row = 1;</code>
     */
    public Builder setRow(
        database.kernel.grpc.query.v1.Row.Builder builderForValue) {
      if (rowBuilder_ == null) {
        row_ = builderForValue.build();
      } else {
        rowBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.minipostgres.query.v1.Row row = 1;</code>
     */
    public Builder mergeRow(database.kernel.grpc.query.v1.Row value) {
      if (rowBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          row_ != null &&
          row_ != database.kernel.grpc.query.v1.Row.getDefaultInstance()) {
          getRowBuilder().mergeFrom(value);
        } else {
          row_ = value;
        }
      } else {
        rowBuilder_.mergeFrom(value);
      }
      if (row_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.minipostgres.query.v1.Row row = 1;</code>
     */
    public Builder clearRow() {
      bitField0_ = (bitField0_ & ~0x00000001);
      row_ = null;
      if (rowBuilder_ != null) {
        rowBuilder_.dispose();
        rowBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.minipostgres.query.v1.Row row = 1;</code>
     */
    public database.kernel.grpc.query.v1.Row.Builder getRowBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRowFieldBuilder().getBuilder();
    }
    /**
     * <code>.minipostgres.query.v1.Row row = 1;</code>
     */
    public database.kernel.grpc.query.v1.RowOrBuilder getRowOrBuilder() {
      if (rowBuilder_ != null) {
        return rowBuilder_.getMessageOrBuilder();
      } else {
        return row_ == null ?
            database.kernel.grpc.query.v1.Row.getDefaultInstance() : row_;
      }
    }
    /**
     * <code>.minipostgres.query.v1.Row row = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        database.kernel.grpc.query.v1.Row, database.kernel.grpc.query.v1.Row.Builder, database.kernel.grpc.query.v1.RowOrBuilder> 
        getRowFieldBuilder() {
      if (rowBuilder_ == null) {
        rowBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            database.kernel.grpc.query.v1.Row, database.kernel.grpc.query.v1.Row.Builder, database.kernel.grpc.query.v1.RowOrBuilder>(
                getRow(),
                getParentForChildren(),
                isClean());
        row_ = null;
      }
      return rowBuilder_;
    }

    private boolean isLast_ ;
    /**
     * <pre>
     * True for the final message in the stream
     * </pre>
     *
     * <code>bool is_last = 2;</code>
     * @return The isLast.
     */
    @java.lang.Override
    public boolean getIsLast() {
      return isLast_;
    }
    /**
     * <pre>
     * True for the final message in the stream
     * </pre>
     *
     * <code>bool is_last = 2;</code>
     * @param value The isLast to set.
     * @return This builder for chaining.
     */
    public Builder setIsLast(boolean value) {

      isLast_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True for the final message in the stream
     * </pre>
     *
     * <code>bool is_last = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLast() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isLast_ = false;
      onChanged();
      return this;
    }

    private database.kernel.grpc.query.v1.ResultSetMeta meta_;
    private com.google.protobuf.SingleFieldBuilder<
        database.kernel.grpc.query.v1.ResultSetMeta, database.kernel.grpc.query.v1.ResultSetMeta.Builder, database.kernel.grpc.query.v1.ResultSetMetaOrBuilder> metaBuilder_;
    /**
     * <pre>
     * Only populated on the first row
     * </pre>
     *
     * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
     * @return Whether the meta field is set.
     */
    public boolean hasMeta() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Only populated on the first row
     * </pre>
     *
     * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
     * @return The meta.
     */
    public database.kernel.grpc.query.v1.ResultSetMeta getMeta() {
      if (metaBuilder_ == null) {
        return meta_ == null ? database.kernel.grpc.query.v1.ResultSetMeta.getDefaultInstance() : meta_;
      } else {
        return metaBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Only populated on the first row
     * </pre>
     *
     * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
     */
    public Builder setMeta(database.kernel.grpc.query.v1.ResultSetMeta value) {
      if (metaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        meta_ = value;
      } else {
        metaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Only populated on the first row
     * </pre>
     *
     * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
     */
    public Builder setMeta(
        database.kernel.grpc.query.v1.ResultSetMeta.Builder builderForValue) {
      if (metaBuilder_ == null) {
        meta_ = builderForValue.build();
      } else {
        metaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Only populated on the first row
     * </pre>
     *
     * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
     */
    public Builder mergeMeta(database.kernel.grpc.query.v1.ResultSetMeta value) {
      if (metaBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          meta_ != null &&
          meta_ != database.kernel.grpc.query.v1.ResultSetMeta.getDefaultInstance()) {
          getMetaBuilder().mergeFrom(value);
        } else {
          meta_ = value;
        }
      } else {
        metaBuilder_.mergeFrom(value);
      }
      if (meta_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Only populated on the first row
     * </pre>
     *
     * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
     */
    public Builder clearMeta() {
      bitField0_ = (bitField0_ & ~0x00000004);
      meta_ = null;
      if (metaBuilder_ != null) {
        metaBuilder_.dispose();
        metaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Only populated on the first row
     * </pre>
     *
     * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
     */
    public database.kernel.grpc.query.v1.ResultSetMeta.Builder getMetaBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getMetaFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Only populated on the first row
     * </pre>
     *
     * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
     */
    public database.kernel.grpc.query.v1.ResultSetMetaOrBuilder getMetaOrBuilder() {
      if (metaBuilder_ != null) {
        return metaBuilder_.getMessageOrBuilder();
      } else {
        return meta_ == null ?
            database.kernel.grpc.query.v1.ResultSetMeta.getDefaultInstance() : meta_;
      }
    }
    /**
     * <pre>
     * Only populated on the first row
     * </pre>
     *
     * <code>.minipostgres.query.v1.ResultSetMeta meta = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        database.kernel.grpc.query.v1.ResultSetMeta, database.kernel.grpc.query.v1.ResultSetMeta.Builder, database.kernel.grpc.query.v1.ResultSetMetaOrBuilder> 
        getMetaFieldBuilder() {
      if (metaBuilder_ == null) {
        metaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            database.kernel.grpc.query.v1.ResultSetMeta, database.kernel.grpc.query.v1.ResultSetMeta.Builder, database.kernel.grpc.query.v1.ResultSetMetaOrBuilder>(
                getMeta(),
                getParentForChildren(),
                isClean());
        meta_ = null;
      }
      return metaBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.query.v1.QueryResultRow)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.query.v1.QueryResultRow)
  private static final database.kernel.grpc.query.v1.QueryResultRow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.query.v1.QueryResultRow();
  }

  public static database.kernel.grpc.query.v1.QueryResultRow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryResultRow>
      PARSER = new com.google.protobuf.AbstractParser<QueryResultRow>() {
    @java.lang.Override
    public QueryResultRow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QueryResultRow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryResultRow> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.query.v1.QueryResultRow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

