// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public interface ResultSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.query.v1.ResultSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  java.util.List<database.kernel.grpc.query.v1.ColumnMeta> 
      getColumnsList();
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  database.kernel.grpc.query.v1.ColumnMeta getColumns(int index);
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  java.util.List<? extends database.kernel.grpc.query.v1.ColumnMetaOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  database.kernel.grpc.query.v1.ColumnMetaOrBuilder getColumnsOrBuilder(
      int index);

  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  java.util.List<database.kernel.grpc.query.v1.Row> 
      getRowsList();
  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  database.kernel.grpc.query.v1.Row getRows(int index);
  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  java.util.List<? extends database.kernel.grpc.query.v1.RowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  database.kernel.grpc.query.v1.RowOrBuilder getRowsOrBuilder(
      int index);

  /**
   * <code>int32 row_count = 3;</code>
   * @return The rowCount.
   */
  int getRowCount();
}
