// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

/**
 * Protobuf type {@code minipostgres.query.v1.ResultSetMeta}
 */
public final class ResultSetMeta extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.query.v1.ResultSetMeta)
    ResultSetMetaOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ResultSetMeta.class.getName());
  }
  // Use ResultSetMeta.newBuilder() to construct.
  private ResultSetMeta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResultSetMeta() {
    columns_ = java.util.Collections.emptyList();
    strategy_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSetMeta_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSetMeta_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.query.v1.ResultSetMeta.class, database.kernel.grpc.query.v1.ResultSetMeta.Builder.class);
  }

  public static final int COLUMNS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<database.kernel.grpc.query.v1.ColumnMeta> columns_;
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public java.util.List<database.kernel.grpc.query.v1.ColumnMeta> getColumnsList() {
    return columns_;
  }
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends database.kernel.grpc.query.v1.ColumnMetaOrBuilder> 
      getColumnsOrBuilderList() {
    return columns_;
  }
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public int getColumnsCount() {
    return columns_.size();
  }
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.ColumnMeta getColumns(int index) {
    return columns_.get(index);
  }
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.ColumnMetaOrBuilder getColumnsOrBuilder(
      int index) {
    return columns_.get(index);
  }

  public static final int STRATEGY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object strategy_ = "";
  /**
   * <code>string strategy = 2;</code>
   * @return The strategy.
   */
  @java.lang.Override
  public java.lang.String getStrategy() {
    java.lang.Object ref = strategy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      strategy_ = s;
      return s;
    }
  }
  /**
   * <code>string strategy = 2;</code>
   * @return The bytes for strategy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStrategyBytes() {
    java.lang.Object ref = strategy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strategy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ELAPSED_NANOS_FIELD_NUMBER = 3;
  private long elapsedNanos_ = 0L;
  /**
   * <code>int64 elapsed_nanos = 3;</code>
   * @return The elapsedNanos.
   */
  @java.lang.Override
  public long getElapsedNanos() {
    return elapsedNanos_;
  }

  public static final int TOTAL_ROWS_FIELD_NUMBER = 4;
  private int totalRows_ = 0;
  /**
   * <code>int32 total_rows = 4;</code>
   * @return The totalRows.
   */
  @java.lang.Override
  public int getTotalRows() {
    return totalRows_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < columns_.size(); i++) {
      output.writeMessage(1, columns_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(strategy_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, strategy_);
    }
    if (elapsedNanos_ != 0L) {
      output.writeInt64(3, elapsedNanos_);
    }
    if (totalRows_ != 0) {
      output.writeInt32(4, totalRows_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < columns_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, columns_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(strategy_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, strategy_);
    }
    if (elapsedNanos_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, elapsedNanos_);
    }
    if (totalRows_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, totalRows_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.query.v1.ResultSetMeta)) {
      return super.equals(obj);
    }
    database.kernel.grpc.query.v1.ResultSetMeta other = (database.kernel.grpc.query.v1.ResultSetMeta) obj;

    if (!getColumnsList()
        .equals(other.getColumnsList())) return false;
    if (!getStrategy()
        .equals(other.getStrategy())) return false;
    if (getElapsedNanos()
        != other.getElapsedNanos()) return false;
    if (getTotalRows()
        != other.getTotalRows()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getColumnsCount() > 0) {
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getColumnsList().hashCode();
    }
    hash = (37 * hash) + STRATEGY_FIELD_NUMBER;
    hash = (53 * hash) + getStrategy().hashCode();
    hash = (37 * hash) + ELAPSED_NANOS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getElapsedNanos());
    hash = (37 * hash) + TOTAL_ROWS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalRows();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.query.v1.ResultSetMeta parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.query.v1.ResultSetMeta parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.ResultSetMeta parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.query.v1.ResultSetMeta prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.query.v1.ResultSetMeta}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.query.v1.ResultSetMeta)
      database.kernel.grpc.query.v1.ResultSetMetaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSetMeta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSetMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.query.v1.ResultSetMeta.class, database.kernel.grpc.query.v1.ResultSetMeta.Builder.class);
    }

    // Construct using database.kernel.grpc.query.v1.ResultSetMeta.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
      } else {
        columns_ = null;
        columnsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      strategy_ = "";
      elapsedNanos_ = 0L;
      totalRows_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSetMeta_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.ResultSetMeta getDefaultInstanceForType() {
      return database.kernel.grpc.query.v1.ResultSetMeta.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.ResultSetMeta build() {
      database.kernel.grpc.query.v1.ResultSetMeta result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.ResultSetMeta buildPartial() {
      database.kernel.grpc.query.v1.ResultSetMeta result = new database.kernel.grpc.query.v1.ResultSetMeta(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(database.kernel.grpc.query.v1.ResultSetMeta result) {
      if (columnsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          columns_ = java.util.Collections.unmodifiableList(columns_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.columns_ = columns_;
      } else {
        result.columns_ = columnsBuilder_.build();
      }
    }

    private void buildPartial0(database.kernel.grpc.query.v1.ResultSetMeta result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.strategy_ = strategy_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.elapsedNanos_ = elapsedNanos_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalRows_ = totalRows_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.query.v1.ResultSetMeta) {
        return mergeFrom((database.kernel.grpc.query.v1.ResultSetMeta)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.query.v1.ResultSetMeta other) {
      if (other == database.kernel.grpc.query.v1.ResultSetMeta.getDefaultInstance()) return this;
      if (columnsBuilder_ == null) {
        if (!other.columns_.isEmpty()) {
          if (columns_.isEmpty()) {
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureColumnsIsMutable();
            columns_.addAll(other.columns_);
          }
          onChanged();
        }
      } else {
        if (!other.columns_.isEmpty()) {
          if (columnsBuilder_.isEmpty()) {
            columnsBuilder_.dispose();
            columnsBuilder_ = null;
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000001);
            columnsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getColumnsFieldBuilder() : null;
          } else {
            columnsBuilder_.addAllMessages(other.columns_);
          }
        }
      }
      if (!other.getStrategy().isEmpty()) {
        strategy_ = other.strategy_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getElapsedNanos() != 0L) {
        setElapsedNanos(other.getElapsedNanos());
      }
      if (other.getTotalRows() != 0) {
        setTotalRows(other.getTotalRows());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              database.kernel.grpc.query.v1.ColumnMeta m =
                  input.readMessage(
                      database.kernel.grpc.query.v1.ColumnMeta.parser(),
                      extensionRegistry);
              if (columnsBuilder_ == null) {
                ensureColumnsIsMutable();
                columns_.add(m);
              } else {
                columnsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              strategy_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              elapsedNanos_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              totalRows_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<database.kernel.grpc.query.v1.ColumnMeta> columns_ =
      java.util.Collections.emptyList();
    private void ensureColumnsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        columns_ = new java.util.ArrayList<database.kernel.grpc.query.v1.ColumnMeta>(columns_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.ColumnMeta, database.kernel.grpc.query.v1.ColumnMeta.Builder, database.kernel.grpc.query.v1.ColumnMetaOrBuilder> columnsBuilder_;

    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.ColumnMeta> getColumnsList() {
      if (columnsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(columns_);
      } else {
        return columnsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public int getColumnsCount() {
      if (columnsBuilder_ == null) {
        return columns_.size();
      } else {
        return columnsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMeta getColumns(int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);
      } else {
        return columnsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder setColumns(
        int index, database.kernel.grpc.query.v1.ColumnMeta value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.set(index, value);
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder setColumns(
        int index, database.kernel.grpc.query.v1.ColumnMeta.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.set(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addColumns(database.kernel.grpc.query.v1.ColumnMeta value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addColumns(
        int index, database.kernel.grpc.query.v1.ColumnMeta value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(index, value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addColumns(
        database.kernel.grpc.query.v1.ColumnMeta.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addColumns(
        int index, database.kernel.grpc.query.v1.ColumnMeta.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addAllColumns(
        java.lang.Iterable<? extends database.kernel.grpc.query.v1.ColumnMeta> values) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columns_);
        onChanged();
      } else {
        columnsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder clearColumns() {
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        columnsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder removeColumns(int index) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.remove(index);
        onChanged();
      } else {
        columnsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMeta.Builder getColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMetaOrBuilder getColumnsOrBuilder(
        int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);  } else {
        return columnsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public java.util.List<? extends database.kernel.grpc.query.v1.ColumnMetaOrBuilder> 
         getColumnsOrBuilderList() {
      if (columnsBuilder_ != null) {
        return columnsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(columns_);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMeta.Builder addColumnsBuilder() {
      return getColumnsFieldBuilder().addBuilder(
          database.kernel.grpc.query.v1.ColumnMeta.getDefaultInstance());
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMeta.Builder addColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().addBuilder(
          index, database.kernel.grpc.query.v1.ColumnMeta.getDefaultInstance());
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.ColumnMeta.Builder> 
         getColumnsBuilderList() {
      return getColumnsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.ColumnMeta, database.kernel.grpc.query.v1.ColumnMeta.Builder, database.kernel.grpc.query.v1.ColumnMetaOrBuilder> 
        getColumnsFieldBuilder() {
      if (columnsBuilder_ == null) {
        columnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            database.kernel.grpc.query.v1.ColumnMeta, database.kernel.grpc.query.v1.ColumnMeta.Builder, database.kernel.grpc.query.v1.ColumnMetaOrBuilder>(
                columns_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        columns_ = null;
      }
      return columnsBuilder_;
    }

    private java.lang.Object strategy_ = "";
    /**
     * <code>string strategy = 2;</code>
     * @return The strategy.
     */
    public java.lang.String getStrategy() {
      java.lang.Object ref = strategy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strategy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string strategy = 2;</code>
     * @return The bytes for strategy.
     */
    public com.google.protobuf.ByteString
        getStrategyBytes() {
      java.lang.Object ref = strategy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strategy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string strategy = 2;</code>
     * @param value The strategy to set.
     * @return This builder for chaining.
     */
    public Builder setStrategy(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      strategy_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string strategy = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStrategy() {
      strategy_ = getDefaultInstance().getStrategy();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string strategy = 2;</code>
     * @param value The bytes for strategy to set.
     * @return This builder for chaining.
     */
    public Builder setStrategyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      strategy_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long elapsedNanos_ ;
    /**
     * <code>int64 elapsed_nanos = 3;</code>
     * @return The elapsedNanos.
     */
    @java.lang.Override
    public long getElapsedNanos() {
      return elapsedNanos_;
    }
    /**
     * <code>int64 elapsed_nanos = 3;</code>
     * @param value The elapsedNanos to set.
     * @return This builder for chaining.
     */
    public Builder setElapsedNanos(long value) {

      elapsedNanos_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 elapsed_nanos = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearElapsedNanos() {
      bitField0_ = (bitField0_ & ~0x00000004);
      elapsedNanos_ = 0L;
      onChanged();
      return this;
    }

    private int totalRows_ ;
    /**
     * <code>int32 total_rows = 4;</code>
     * @return The totalRows.
     */
    @java.lang.Override
    public int getTotalRows() {
      return totalRows_;
    }
    /**
     * <code>int32 total_rows = 4;</code>
     * @param value The totalRows to set.
     * @return This builder for chaining.
     */
    public Builder setTotalRows(int value) {

      totalRows_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_rows = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalRows() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalRows_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.query.v1.ResultSetMeta)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.query.v1.ResultSetMeta)
  private static final database.kernel.grpc.query.v1.ResultSetMeta DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.query.v1.ResultSetMeta();
  }

  public static database.kernel.grpc.query.v1.ResultSetMeta getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResultSetMeta>
      PARSER = new com.google.protobuf.AbstractParser<ResultSetMeta>() {
    @java.lang.Override
    public ResultSetMeta parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResultSetMeta> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResultSetMeta> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.query.v1.ResultSetMeta getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

