// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

/**
 * Protobuf type {@code minipostgres.query.v1.ResultSet}
 */
public final class ResultSet extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.query.v1.ResultSet)
    ResultSetOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ResultSet.class.getName());
  }
  // Use ResultSet.newBuilder() to construct.
  private ResultSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResultSet() {
    columns_ = java.util.Collections.emptyList();
    rows_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.query.v1.ResultSet.class, database.kernel.grpc.query.v1.ResultSet.Builder.class);
  }

  public static final int COLUMNS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<database.kernel.grpc.query.v1.ColumnMeta> columns_;
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public java.util.List<database.kernel.grpc.query.v1.ColumnMeta> getColumnsList() {
    return columns_;
  }
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends database.kernel.grpc.query.v1.ColumnMetaOrBuilder> 
      getColumnsOrBuilderList() {
    return columns_;
  }
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public int getColumnsCount() {
    return columns_.size();
  }
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.ColumnMeta getColumns(int index) {
    return columns_.get(index);
  }
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.ColumnMetaOrBuilder getColumnsOrBuilder(
      int index) {
    return columns_.get(index);
  }

  public static final int ROWS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<database.kernel.grpc.query.v1.Row> rows_;
  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  @java.lang.Override
  public java.util.List<database.kernel.grpc.query.v1.Row> getRowsList() {
    return rows_;
  }
  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends database.kernel.grpc.query.v1.RowOrBuilder> 
      getRowsOrBuilderList() {
    return rows_;
  }
  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  @java.lang.Override
  public int getRowsCount() {
    return rows_.size();
  }
  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.Row getRows(int index) {
    return rows_.get(index);
  }
  /**
   * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.RowOrBuilder getRowsOrBuilder(
      int index) {
    return rows_.get(index);
  }

  public static final int ROW_COUNT_FIELD_NUMBER = 3;
  private int rowCount_ = 0;
  /**
   * <code>int32 row_count = 3;</code>
   * @return The rowCount.
   */
  @java.lang.Override
  public int getRowCount() {
    return rowCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < columns_.size(); i++) {
      output.writeMessage(1, columns_.get(i));
    }
    for (int i = 0; i < rows_.size(); i++) {
      output.writeMessage(2, rows_.get(i));
    }
    if (rowCount_ != 0) {
      output.writeInt32(3, rowCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < columns_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, columns_.get(i));
    }
    for (int i = 0; i < rows_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, rows_.get(i));
    }
    if (rowCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, rowCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.query.v1.ResultSet)) {
      return super.equals(obj);
    }
    database.kernel.grpc.query.v1.ResultSet other = (database.kernel.grpc.query.v1.ResultSet) obj;

    if (!getColumnsList()
        .equals(other.getColumnsList())) return false;
    if (!getRowsList()
        .equals(other.getRowsList())) return false;
    if (getRowCount()
        != other.getRowCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getColumnsCount() > 0) {
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getColumnsList().hashCode();
    }
    if (getRowsCount() > 0) {
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRowsList().hashCode();
    }
    hash = (37 * hash) + ROW_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRowCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.query.v1.ResultSet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.ResultSet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ResultSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.ResultSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ResultSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.ResultSet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ResultSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.ResultSet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.query.v1.ResultSet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.query.v1.ResultSet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.ResultSet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.ResultSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.query.v1.ResultSet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.query.v1.ResultSet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.query.v1.ResultSet)
      database.kernel.grpc.query.v1.ResultSetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.query.v1.ResultSet.class, database.kernel.grpc.query.v1.ResultSet.Builder.class);
    }

    // Construct using database.kernel.grpc.query.v1.ResultSet.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
      } else {
        columns_ = null;
        columnsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
      } else {
        rows_ = null;
        rowsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      rowCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_ResultSet_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.ResultSet getDefaultInstanceForType() {
      return database.kernel.grpc.query.v1.ResultSet.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.ResultSet build() {
      database.kernel.grpc.query.v1.ResultSet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.ResultSet buildPartial() {
      database.kernel.grpc.query.v1.ResultSet result = new database.kernel.grpc.query.v1.ResultSet(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(database.kernel.grpc.query.v1.ResultSet result) {
      if (columnsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          columns_ = java.util.Collections.unmodifiableList(columns_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.columns_ = columns_;
      } else {
        result.columns_ = columnsBuilder_.build();
      }
      if (rowsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rows_ = rows_;
      } else {
        result.rows_ = rowsBuilder_.build();
      }
    }

    private void buildPartial0(database.kernel.grpc.query.v1.ResultSet result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rowCount_ = rowCount_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.query.v1.ResultSet) {
        return mergeFrom((database.kernel.grpc.query.v1.ResultSet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.query.v1.ResultSet other) {
      if (other == database.kernel.grpc.query.v1.ResultSet.getDefaultInstance()) return this;
      if (columnsBuilder_ == null) {
        if (!other.columns_.isEmpty()) {
          if (columns_.isEmpty()) {
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureColumnsIsMutable();
            columns_.addAll(other.columns_);
          }
          onChanged();
        }
      } else {
        if (!other.columns_.isEmpty()) {
          if (columnsBuilder_.isEmpty()) {
            columnsBuilder_.dispose();
            columnsBuilder_ = null;
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000001);
            columnsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getColumnsFieldBuilder() : null;
          } else {
            columnsBuilder_.addAllMessages(other.columns_);
          }
        }
      }
      if (rowsBuilder_ == null) {
        if (!other.rows_.isEmpty()) {
          if (rows_.isEmpty()) {
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRowsIsMutable();
            rows_.addAll(other.rows_);
          }
          onChanged();
        }
      } else {
        if (!other.rows_.isEmpty()) {
          if (rowsBuilder_.isEmpty()) {
            rowsBuilder_.dispose();
            rowsBuilder_ = null;
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
            rowsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getRowsFieldBuilder() : null;
          } else {
            rowsBuilder_.addAllMessages(other.rows_);
          }
        }
      }
      if (other.getRowCount() != 0) {
        setRowCount(other.getRowCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              database.kernel.grpc.query.v1.ColumnMeta m =
                  input.readMessage(
                      database.kernel.grpc.query.v1.ColumnMeta.parser(),
                      extensionRegistry);
              if (columnsBuilder_ == null) {
                ensureColumnsIsMutable();
                columns_.add(m);
              } else {
                columnsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              database.kernel.grpc.query.v1.Row m =
                  input.readMessage(
                      database.kernel.grpc.query.v1.Row.parser(),
                      extensionRegistry);
              if (rowsBuilder_ == null) {
                ensureRowsIsMutable();
                rows_.add(m);
              } else {
                rowsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 24: {
              rowCount_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<database.kernel.grpc.query.v1.ColumnMeta> columns_ =
      java.util.Collections.emptyList();
    private void ensureColumnsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        columns_ = new java.util.ArrayList<database.kernel.grpc.query.v1.ColumnMeta>(columns_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.ColumnMeta, database.kernel.grpc.query.v1.ColumnMeta.Builder, database.kernel.grpc.query.v1.ColumnMetaOrBuilder> columnsBuilder_;

    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.ColumnMeta> getColumnsList() {
      if (columnsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(columns_);
      } else {
        return columnsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public int getColumnsCount() {
      if (columnsBuilder_ == null) {
        return columns_.size();
      } else {
        return columnsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMeta getColumns(int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);
      } else {
        return columnsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder setColumns(
        int index, database.kernel.grpc.query.v1.ColumnMeta value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.set(index, value);
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder setColumns(
        int index, database.kernel.grpc.query.v1.ColumnMeta.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.set(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addColumns(database.kernel.grpc.query.v1.ColumnMeta value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addColumns(
        int index, database.kernel.grpc.query.v1.ColumnMeta value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(index, value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addColumns(
        database.kernel.grpc.query.v1.ColumnMeta.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addColumns(
        int index, database.kernel.grpc.query.v1.ColumnMeta.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder addAllColumns(
        java.lang.Iterable<? extends database.kernel.grpc.query.v1.ColumnMeta> values) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columns_);
        onChanged();
      } else {
        columnsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder clearColumns() {
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        columnsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public Builder removeColumns(int index) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.remove(index);
        onChanged();
      } else {
        columnsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMeta.Builder getColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMetaOrBuilder getColumnsOrBuilder(
        int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);  } else {
        return columnsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public java.util.List<? extends database.kernel.grpc.query.v1.ColumnMetaOrBuilder> 
         getColumnsOrBuilderList() {
      if (columnsBuilder_ != null) {
        return columnsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(columns_);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMeta.Builder addColumnsBuilder() {
      return getColumnsFieldBuilder().addBuilder(
          database.kernel.grpc.query.v1.ColumnMeta.getDefaultInstance());
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public database.kernel.grpc.query.v1.ColumnMeta.Builder addColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().addBuilder(
          index, database.kernel.grpc.query.v1.ColumnMeta.getDefaultInstance());
    }
    /**
     * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 1;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.ColumnMeta.Builder> 
         getColumnsBuilderList() {
      return getColumnsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.ColumnMeta, database.kernel.grpc.query.v1.ColumnMeta.Builder, database.kernel.grpc.query.v1.ColumnMetaOrBuilder> 
        getColumnsFieldBuilder() {
      if (columnsBuilder_ == null) {
        columnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            database.kernel.grpc.query.v1.ColumnMeta, database.kernel.grpc.query.v1.ColumnMeta.Builder, database.kernel.grpc.query.v1.ColumnMetaOrBuilder>(
                columns_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        columns_ = null;
      }
      return columnsBuilder_;
    }

    private java.util.List<database.kernel.grpc.query.v1.Row> rows_ =
      java.util.Collections.emptyList();
    private void ensureRowsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        rows_ = new java.util.ArrayList<database.kernel.grpc.query.v1.Row>(rows_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.Row, database.kernel.grpc.query.v1.Row.Builder, database.kernel.grpc.query.v1.RowOrBuilder> rowsBuilder_;

    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.Row> getRowsList() {
      if (rowsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rows_);
      } else {
        return rowsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public int getRowsCount() {
      if (rowsBuilder_ == null) {
        return rows_.size();
      } else {
        return rowsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public database.kernel.grpc.query.v1.Row getRows(int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);
      } else {
        return rowsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public Builder setRows(
        int index, database.kernel.grpc.query.v1.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.set(index, value);
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public Builder setRows(
        int index, database.kernel.grpc.query.v1.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.set(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public Builder addRows(database.kernel.grpc.query.v1.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public Builder addRows(
        int index, database.kernel.grpc.query.v1.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(index, value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public Builder addRows(
        database.kernel.grpc.query.v1.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public Builder addRows(
        int index, database.kernel.grpc.query.v1.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public Builder addAllRows(
        java.lang.Iterable<? extends database.kernel.grpc.query.v1.Row> values) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rows_);
        onChanged();
      } else {
        rowsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public Builder clearRows() {
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public Builder removeRows(int index) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.remove(index);
        onChanged();
      } else {
        rowsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public database.kernel.grpc.query.v1.Row.Builder getRowsBuilder(
        int index) {
      return getRowsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public database.kernel.grpc.query.v1.RowOrBuilder getRowsOrBuilder(
        int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);  } else {
        return rowsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public java.util.List<? extends database.kernel.grpc.query.v1.RowOrBuilder> 
         getRowsOrBuilderList() {
      if (rowsBuilder_ != null) {
        return rowsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rows_);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public database.kernel.grpc.query.v1.Row.Builder addRowsBuilder() {
      return getRowsFieldBuilder().addBuilder(
          database.kernel.grpc.query.v1.Row.getDefaultInstance());
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public database.kernel.grpc.query.v1.Row.Builder addRowsBuilder(
        int index) {
      return getRowsFieldBuilder().addBuilder(
          index, database.kernel.grpc.query.v1.Row.getDefaultInstance());
    }
    /**
     * <code>repeated .minipostgres.query.v1.Row rows = 2;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.Row.Builder> 
         getRowsBuilderList() {
      return getRowsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.Row, database.kernel.grpc.query.v1.Row.Builder, database.kernel.grpc.query.v1.RowOrBuilder> 
        getRowsFieldBuilder() {
      if (rowsBuilder_ == null) {
        rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            database.kernel.grpc.query.v1.Row, database.kernel.grpc.query.v1.Row.Builder, database.kernel.grpc.query.v1.RowOrBuilder>(
                rows_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        rows_ = null;
      }
      return rowsBuilder_;
    }

    private int rowCount_ ;
    /**
     * <code>int32 row_count = 3;</code>
     * @return The rowCount.
     */
    @java.lang.Override
    public int getRowCount() {
      return rowCount_;
    }
    /**
     * <code>int32 row_count = 3;</code>
     * @param value The rowCount to set.
     * @return This builder for chaining.
     */
    public Builder setRowCount(int value) {

      rowCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 row_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRowCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rowCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.query.v1.ResultSet)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.query.v1.ResultSet)
  private static final database.kernel.grpc.query.v1.ResultSet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.query.v1.ResultSet();
  }

  public static database.kernel.grpc.query.v1.ResultSet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResultSet>
      PARSER = new com.google.protobuf.AbstractParser<ResultSet>() {
    @java.lang.Override
    public ResultSet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResultSet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResultSet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.query.v1.ResultSet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

