// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public interface RowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.query.v1.Row)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .minipostgres.query.v1.Value values = 1;</code>
   */
  java.util.List<database.kernel.grpc.query.v1.Value> 
      getValuesList();
  /**
   * <code>repeated .minipostgres.query.v1.Value values = 1;</code>
   */
  database.kernel.grpc.query.v1.Value getValues(int index);
  /**
   * <code>repeated .minipostgres.query.v1.Value values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .minipostgres.query.v1.Value values = 1;</code>
   */
  java.util.List<? extends database.kernel.grpc.query.v1.ValueOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .minipostgres.query.v1.Value values = 1;</code>
   */
  database.kernel.grpc.query.v1.ValueOrBuilder getValuesOrBuilder(
      int index);
}
