// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

/**
 * Protobuf type {@code minipostgres.query.v1.StateResponse}
 */
public final class StateResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.query.v1.StateResponse)
    StateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      StateResponse.class.getName());
  }
  // Use StateResponse.newBuilder() to construct.
  private StateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StateResponse() {
    dataDirectory_ = "";
    tables_ = java.util.Collections.emptyList();
    indexes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    dataFiles_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_StateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_StateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.query.v1.StateResponse.class, database.kernel.grpc.query.v1.StateResponse.Builder.class);
  }

  public static final int OK_FIELD_NUMBER = 1;
  private boolean ok_ = false;
  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  @java.lang.Override
  public boolean getOk() {
    return ok_;
  }

  public static final int DATA_DIRECTORY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataDirectory_ = "";
  /**
   * <code>string data_directory = 2;</code>
   * @return The dataDirectory.
   */
  @java.lang.Override
  public java.lang.String getDataDirectory() {
    java.lang.Object ref = dataDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>string data_directory = 2;</code>
   * @return The bytes for dataDirectory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataDirectoryBytes() {
    java.lang.Object ref = dataDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLE_COUNT_FIELD_NUMBER = 3;
  private int tableCount_ = 0;
  /**
   * <code>int32 table_count = 3;</code>
   * @return The tableCount.
   */
  @java.lang.Override
  public int getTableCount() {
    return tableCount_;
  }

  public static final int TABLES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<database.kernel.grpc.query.v1.TableInfo> tables_;
  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  @java.lang.Override
  public java.util.List<database.kernel.grpc.query.v1.TableInfo> getTablesList() {
    return tables_;
  }
  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends database.kernel.grpc.query.v1.TableInfoOrBuilder> 
      getTablesOrBuilderList() {
    return tables_;
  }
  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  @java.lang.Override
  public int getTablesCount() {
    return tables_.size();
  }
  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.TableInfo getTables(int index) {
    return tables_.get(index);
  }
  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  @java.lang.Override
  public database.kernel.grpc.query.v1.TableInfoOrBuilder getTablesOrBuilder(
      int index) {
    return tables_.get(index);
  }

  public static final int INDEXES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList indexes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string indexes = 5;</code>
   * @return A list containing the indexes.
   */
  public com.google.protobuf.ProtocolStringList
      getIndexesList() {
    return indexes_;
  }
  /**
   * <code>repeated string indexes = 5;</code>
   * @return The count of indexes.
   */
  public int getIndexesCount() {
    return indexes_.size();
  }
  /**
   * <code>repeated string indexes = 5;</code>
   * @param index The index of the element to return.
   * @return The indexes at the given index.
   */
  public java.lang.String getIndexes(int index) {
    return indexes_.get(index);
  }
  /**
   * <code>repeated string indexes = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the indexes at the given index.
   */
  public com.google.protobuf.ByteString
      getIndexesBytes(int index) {
    return indexes_.getByteString(index);
  }

  public static final int DATA_FILES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList dataFiles_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string data_files = 6;</code>
   * @return A list containing the dataFiles.
   */
  public com.google.protobuf.ProtocolStringList
      getDataFilesList() {
    return dataFiles_;
  }
  /**
   * <code>repeated string data_files = 6;</code>
   * @return The count of dataFiles.
   */
  public int getDataFilesCount() {
    return dataFiles_.size();
  }
  /**
   * <code>repeated string data_files = 6;</code>
   * @param index The index of the element to return.
   * @return The dataFiles at the given index.
   */
  public java.lang.String getDataFiles(int index) {
    return dataFiles_.get(index);
  }
  /**
   * <code>repeated string data_files = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the dataFiles at the given index.
   */
  public com.google.protobuf.ByteString
      getDataFilesBytes(int index) {
    return dataFiles_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ok_ != false) {
      output.writeBool(1, ok_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataDirectory_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, dataDirectory_);
    }
    if (tableCount_ != 0) {
      output.writeInt32(3, tableCount_);
    }
    for (int i = 0; i < tables_.size(); i++) {
      output.writeMessage(4, tables_.get(i));
    }
    for (int i = 0; i < indexes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, indexes_.getRaw(i));
    }
    for (int i = 0; i < dataFiles_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, dataFiles_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ok_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, ok_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dataDirectory_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, dataDirectory_);
    }
    if (tableCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, tableCount_);
    }
    for (int i = 0; i < tables_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, tables_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < indexes_.size(); i++) {
        dataSize += computeStringSizeNoTag(indexes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIndexesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < dataFiles_.size(); i++) {
        dataSize += computeStringSizeNoTag(dataFiles_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDataFilesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.query.v1.StateResponse)) {
      return super.equals(obj);
    }
    database.kernel.grpc.query.v1.StateResponse other = (database.kernel.grpc.query.v1.StateResponse) obj;

    if (getOk()
        != other.getOk()) return false;
    if (!getDataDirectory()
        .equals(other.getDataDirectory())) return false;
    if (getTableCount()
        != other.getTableCount()) return false;
    if (!getTablesList()
        .equals(other.getTablesList())) return false;
    if (!getIndexesList()
        .equals(other.getIndexesList())) return false;
    if (!getDataFilesList()
        .equals(other.getDataFilesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOk());
    hash = (37 * hash) + DATA_DIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getDataDirectory().hashCode();
    hash = (37 * hash) + TABLE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTableCount();
    if (getTablesCount() > 0) {
      hash = (37 * hash) + TABLES_FIELD_NUMBER;
      hash = (53 * hash) + getTablesList().hashCode();
    }
    if (getIndexesCount() > 0) {
      hash = (37 * hash) + INDEXES_FIELD_NUMBER;
      hash = (53 * hash) + getIndexesList().hashCode();
    }
    if (getDataFilesCount() > 0) {
      hash = (37 * hash) + DATA_FILES_FIELD_NUMBER;
      hash = (53 * hash) + getDataFilesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.query.v1.StateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.StateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.StateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.StateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.StateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.StateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.StateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.StateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.query.v1.StateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.query.v1.StateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.StateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.StateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.query.v1.StateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.query.v1.StateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.query.v1.StateResponse)
      database.kernel.grpc.query.v1.StateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_StateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_StateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.query.v1.StateResponse.class, database.kernel.grpc.query.v1.StateResponse.Builder.class);
    }

    // Construct using database.kernel.grpc.query.v1.StateResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ok_ = false;
      dataDirectory_ = "";
      tableCount_ = 0;
      if (tablesBuilder_ == null) {
        tables_ = java.util.Collections.emptyList();
      } else {
        tables_ = null;
        tablesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      indexes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      dataFiles_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_StateResponse_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.StateResponse getDefaultInstanceForType() {
      return database.kernel.grpc.query.v1.StateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.StateResponse build() {
      database.kernel.grpc.query.v1.StateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.StateResponse buildPartial() {
      database.kernel.grpc.query.v1.StateResponse result = new database.kernel.grpc.query.v1.StateResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(database.kernel.grpc.query.v1.StateResponse result) {
      if (tablesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          tables_ = java.util.Collections.unmodifiableList(tables_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.tables_ = tables_;
      } else {
        result.tables_ = tablesBuilder_.build();
      }
    }

    private void buildPartial0(database.kernel.grpc.query.v1.StateResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ok_ = ok_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.dataDirectory_ = dataDirectory_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tableCount_ = tableCount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        indexes_.makeImmutable();
        result.indexes_ = indexes_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        dataFiles_.makeImmutable();
        result.dataFiles_ = dataFiles_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.query.v1.StateResponse) {
        return mergeFrom((database.kernel.grpc.query.v1.StateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.query.v1.StateResponse other) {
      if (other == database.kernel.grpc.query.v1.StateResponse.getDefaultInstance()) return this;
      if (other.getOk() != false) {
        setOk(other.getOk());
      }
      if (!other.getDataDirectory().isEmpty()) {
        dataDirectory_ = other.dataDirectory_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTableCount() != 0) {
        setTableCount(other.getTableCount());
      }
      if (tablesBuilder_ == null) {
        if (!other.tables_.isEmpty()) {
          if (tables_.isEmpty()) {
            tables_ = other.tables_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTablesIsMutable();
            tables_.addAll(other.tables_);
          }
          onChanged();
        }
      } else {
        if (!other.tables_.isEmpty()) {
          if (tablesBuilder_.isEmpty()) {
            tablesBuilder_.dispose();
            tablesBuilder_ = null;
            tables_ = other.tables_;
            bitField0_ = (bitField0_ & ~0x00000008);
            tablesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTablesFieldBuilder() : null;
          } else {
            tablesBuilder_.addAllMessages(other.tables_);
          }
        }
      }
      if (!other.indexes_.isEmpty()) {
        if (indexes_.isEmpty()) {
          indexes_ = other.indexes_;
          bitField0_ |= 0x00000010;
        } else {
          ensureIndexesIsMutable();
          indexes_.addAll(other.indexes_);
        }
        onChanged();
      }
      if (!other.dataFiles_.isEmpty()) {
        if (dataFiles_.isEmpty()) {
          dataFiles_ = other.dataFiles_;
          bitField0_ |= 0x00000020;
        } else {
          ensureDataFilesIsMutable();
          dataFiles_.addAll(other.dataFiles_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ok_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              dataDirectory_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              tableCount_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              database.kernel.grpc.query.v1.TableInfo m =
                  input.readMessage(
                      database.kernel.grpc.query.v1.TableInfo.parser(),
                      extensionRegistry);
              if (tablesBuilder_ == null) {
                ensureTablesIsMutable();
                tables_.add(m);
              } else {
                tablesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureIndexesIsMutable();
              indexes_.add(s);
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureDataFilesIsMutable();
              dataFiles_.add(s);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean ok_ ;
    /**
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return ok_;
    }
    /**
     * <code>bool ok = 1;</code>
     * @param value The ok to set.
     * @return This builder for chaining.
     */
    public Builder setOk(boolean value) {

      ok_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool ok = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOk() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ok_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object dataDirectory_ = "";
    /**
     * <code>string data_directory = 2;</code>
     * @return The dataDirectory.
     */
    public java.lang.String getDataDirectory() {
      java.lang.Object ref = dataDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data_directory = 2;</code>
     * @return The bytes for dataDirectory.
     */
    public com.google.protobuf.ByteString
        getDataDirectoryBytes() {
      java.lang.Object ref = dataDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data_directory = 2;</code>
     * @param value The dataDirectory to set.
     * @return This builder for chaining.
     */
    public Builder setDataDirectory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataDirectory_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string data_directory = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataDirectory() {
      dataDirectory_ = getDefaultInstance().getDataDirectory();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string data_directory = 2;</code>
     * @param value The bytes for dataDirectory to set.
     * @return This builder for chaining.
     */
    public Builder setDataDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataDirectory_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int tableCount_ ;
    /**
     * <code>int32 table_count = 3;</code>
     * @return The tableCount.
     */
    @java.lang.Override
    public int getTableCount() {
      return tableCount_;
    }
    /**
     * <code>int32 table_count = 3;</code>
     * @param value The tableCount to set.
     * @return This builder for chaining.
     */
    public Builder setTableCount(int value) {

      tableCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 table_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tableCount_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<database.kernel.grpc.query.v1.TableInfo> tables_ =
      java.util.Collections.emptyList();
    private void ensureTablesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        tables_ = new java.util.ArrayList<database.kernel.grpc.query.v1.TableInfo>(tables_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.TableInfo, database.kernel.grpc.query.v1.TableInfo.Builder, database.kernel.grpc.query.v1.TableInfoOrBuilder> tablesBuilder_;

    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.TableInfo> getTablesList() {
      if (tablesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tables_);
      } else {
        return tablesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public int getTablesCount() {
      if (tablesBuilder_ == null) {
        return tables_.size();
      } else {
        return tablesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public database.kernel.grpc.query.v1.TableInfo getTables(int index) {
      if (tablesBuilder_ == null) {
        return tables_.get(index);
      } else {
        return tablesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public Builder setTables(
        int index, database.kernel.grpc.query.v1.TableInfo value) {
      if (tablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTablesIsMutable();
        tables_.set(index, value);
        onChanged();
      } else {
        tablesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public Builder setTables(
        int index, database.kernel.grpc.query.v1.TableInfo.Builder builderForValue) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        tables_.set(index, builderForValue.build());
        onChanged();
      } else {
        tablesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public Builder addTables(database.kernel.grpc.query.v1.TableInfo value) {
      if (tablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTablesIsMutable();
        tables_.add(value);
        onChanged();
      } else {
        tablesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public Builder addTables(
        int index, database.kernel.grpc.query.v1.TableInfo value) {
      if (tablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTablesIsMutable();
        tables_.add(index, value);
        onChanged();
      } else {
        tablesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public Builder addTables(
        database.kernel.grpc.query.v1.TableInfo.Builder builderForValue) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        tables_.add(builderForValue.build());
        onChanged();
      } else {
        tablesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public Builder addTables(
        int index, database.kernel.grpc.query.v1.TableInfo.Builder builderForValue) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        tables_.add(index, builderForValue.build());
        onChanged();
      } else {
        tablesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public Builder addAllTables(
        java.lang.Iterable<? extends database.kernel.grpc.query.v1.TableInfo> values) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tables_);
        onChanged();
      } else {
        tablesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public Builder clearTables() {
      if (tablesBuilder_ == null) {
        tables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        tablesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public Builder removeTables(int index) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        tables_.remove(index);
        onChanged();
      } else {
        tablesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public database.kernel.grpc.query.v1.TableInfo.Builder getTablesBuilder(
        int index) {
      return getTablesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public database.kernel.grpc.query.v1.TableInfoOrBuilder getTablesOrBuilder(
        int index) {
      if (tablesBuilder_ == null) {
        return tables_.get(index);  } else {
        return tablesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public java.util.List<? extends database.kernel.grpc.query.v1.TableInfoOrBuilder> 
         getTablesOrBuilderList() {
      if (tablesBuilder_ != null) {
        return tablesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tables_);
      }
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public database.kernel.grpc.query.v1.TableInfo.Builder addTablesBuilder() {
      return getTablesFieldBuilder().addBuilder(
          database.kernel.grpc.query.v1.TableInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public database.kernel.grpc.query.v1.TableInfo.Builder addTablesBuilder(
        int index) {
      return getTablesFieldBuilder().addBuilder(
          index, database.kernel.grpc.query.v1.TableInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
     */
    public java.util.List<database.kernel.grpc.query.v1.TableInfo.Builder> 
         getTablesBuilderList() {
      return getTablesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        database.kernel.grpc.query.v1.TableInfo, database.kernel.grpc.query.v1.TableInfo.Builder, database.kernel.grpc.query.v1.TableInfoOrBuilder> 
        getTablesFieldBuilder() {
      if (tablesBuilder_ == null) {
        tablesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            database.kernel.grpc.query.v1.TableInfo, database.kernel.grpc.query.v1.TableInfo.Builder, database.kernel.grpc.query.v1.TableInfoOrBuilder>(
                tables_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        tables_ = null;
      }
      return tablesBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList indexes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureIndexesIsMutable() {
      if (!indexes_.isModifiable()) {
        indexes_ = new com.google.protobuf.LazyStringArrayList(indexes_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated string indexes = 5;</code>
     * @return A list containing the indexes.
     */
    public com.google.protobuf.ProtocolStringList
        getIndexesList() {
      indexes_.makeImmutable();
      return indexes_;
    }
    /**
     * <code>repeated string indexes = 5;</code>
     * @return The count of indexes.
     */
    public int getIndexesCount() {
      return indexes_.size();
    }
    /**
     * <code>repeated string indexes = 5;</code>
     * @param index The index of the element to return.
     * @return The indexes at the given index.
     */
    public java.lang.String getIndexes(int index) {
      return indexes_.get(index);
    }
    /**
     * <code>repeated string indexes = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the indexes at the given index.
     */
    public com.google.protobuf.ByteString
        getIndexesBytes(int index) {
      return indexes_.getByteString(index);
    }
    /**
     * <code>repeated string indexes = 5;</code>
     * @param index The index to set the value at.
     * @param value The indexes to set.
     * @return This builder for chaining.
     */
    public Builder setIndexes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureIndexesIsMutable();
      indexes_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string indexes = 5;</code>
     * @param value The indexes to add.
     * @return This builder for chaining.
     */
    public Builder addIndexes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureIndexesIsMutable();
      indexes_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string indexes = 5;</code>
     * @param values The indexes to add.
     * @return This builder for chaining.
     */
    public Builder addAllIndexes(
        java.lang.Iterable<java.lang.String> values) {
      ensureIndexesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, indexes_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string indexes = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndexes() {
      indexes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string indexes = 5;</code>
     * @param value The bytes of the indexes to add.
     * @return This builder for chaining.
     */
    public Builder addIndexesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureIndexesIsMutable();
      indexes_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList dataFiles_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureDataFilesIsMutable() {
      if (!dataFiles_.isModifiable()) {
        dataFiles_ = new com.google.protobuf.LazyStringArrayList(dataFiles_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string data_files = 6;</code>
     * @return A list containing the dataFiles.
     */
    public com.google.protobuf.ProtocolStringList
        getDataFilesList() {
      dataFiles_.makeImmutable();
      return dataFiles_;
    }
    /**
     * <code>repeated string data_files = 6;</code>
     * @return The count of dataFiles.
     */
    public int getDataFilesCount() {
      return dataFiles_.size();
    }
    /**
     * <code>repeated string data_files = 6;</code>
     * @param index The index of the element to return.
     * @return The dataFiles at the given index.
     */
    public java.lang.String getDataFiles(int index) {
      return dataFiles_.get(index);
    }
    /**
     * <code>repeated string data_files = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the dataFiles at the given index.
     */
    public com.google.protobuf.ByteString
        getDataFilesBytes(int index) {
      return dataFiles_.getByteString(index);
    }
    /**
     * <code>repeated string data_files = 6;</code>
     * @param index The index to set the value at.
     * @param value The dataFiles to set.
     * @return This builder for chaining.
     */
    public Builder setDataFiles(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDataFilesIsMutable();
      dataFiles_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string data_files = 6;</code>
     * @param value The dataFiles to add.
     * @return This builder for chaining.
     */
    public Builder addDataFiles(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDataFilesIsMutable();
      dataFiles_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string data_files = 6;</code>
     * @param values The dataFiles to add.
     * @return This builder for chaining.
     */
    public Builder addAllDataFiles(
        java.lang.Iterable<java.lang.String> values) {
      ensureDataFilesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, dataFiles_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string data_files = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataFiles() {
      dataFiles_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string data_files = 6;</code>
     * @param value The bytes of the dataFiles to add.
     * @return This builder for chaining.
     */
    public Builder addDataFilesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureDataFilesIsMutable();
      dataFiles_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.query.v1.StateResponse)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.query.v1.StateResponse)
  private static final database.kernel.grpc.query.v1.StateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.query.v1.StateResponse();
  }

  public static database.kernel.grpc.query.v1.StateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StateResponse>
      PARSER = new com.google.protobuf.AbstractParser<StateResponse>() {
    @java.lang.Override
    public StateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.query.v1.StateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

