// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public interface StateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.query.v1.StateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <code>string data_directory = 2;</code>
   * @return The dataDirectory.
   */
  java.lang.String getDataDirectory();
  /**
   * <code>string data_directory = 2;</code>
   * @return The bytes for dataDirectory.
   */
  com.google.protobuf.ByteString
      getDataDirectoryBytes();

  /**
   * <code>int32 table_count = 3;</code>
   * @return The tableCount.
   */
  int getTableCount();

  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  java.util.List<database.kernel.grpc.query.v1.TableInfo> 
      getTablesList();
  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  database.kernel.grpc.query.v1.TableInfo getTables(int index);
  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  int getTablesCount();
  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  java.util.List<? extends database.kernel.grpc.query.v1.TableInfoOrBuilder> 
      getTablesOrBuilderList();
  /**
   * <code>repeated .minipostgres.query.v1.TableInfo tables = 4;</code>
   */
  database.kernel.grpc.query.v1.TableInfoOrBuilder getTablesOrBuilder(
      int index);

  /**
   * <code>repeated string indexes = 5;</code>
   * @return A list containing the indexes.
   */
  java.util.List<java.lang.String>
      getIndexesList();
  /**
   * <code>repeated string indexes = 5;</code>
   * @return The count of indexes.
   */
  int getIndexesCount();
  /**
   * <code>repeated string indexes = 5;</code>
   * @param index The index of the element to return.
   * @return The indexes at the given index.
   */
  java.lang.String getIndexes(int index);
  /**
   * <code>repeated string indexes = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the indexes at the given index.
   */
  com.google.protobuf.ByteString
      getIndexesBytes(int index);

  /**
   * <code>repeated string data_files = 6;</code>
   * @return A list containing the dataFiles.
   */
  java.util.List<java.lang.String>
      getDataFilesList();
  /**
   * <code>repeated string data_files = 6;</code>
   * @return The count of dataFiles.
   */
  int getDataFilesCount();
  /**
   * <code>repeated string data_files = 6;</code>
   * @param index The index of the element to return.
   * @return The dataFiles at the given index.
   */
  java.lang.String getDataFiles(int index);
  /**
   * <code>repeated string data_files = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the dataFiles at the given index.
   */
  com.google.protobuf.ByteString
      getDataFilesBytes(int index);
}
