// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public interface TableInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.query.v1.TableInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Human-readable schema description
   * </pre>
   *
   * <code>string schema = 2;</code>
   * @return The schema.
   */
  java.lang.String getSchema();
  /**
   * <pre>
   * Human-readable schema description
   * </pre>
   *
   * <code>string schema = 2;</code>
   * @return The bytes for schema.
   */
  com.google.protobuf.ByteString
      getSchemaBytes();

  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 3;</code>
   */
  java.util.List<database.kernel.grpc.query.v1.ColumnMeta> 
      getColumnsList();
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 3;</code>
   */
  database.kernel.grpc.query.v1.ColumnMeta getColumns(int index);
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 3;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 3;</code>
   */
  java.util.List<? extends database.kernel.grpc.query.v1.ColumnMetaOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .minipostgres.query.v1.ColumnMeta columns = 3;</code>
   */
  database.kernel.grpc.query.v1.ColumnMetaOrBuilder getColumnsOrBuilder(
      int index);
}
