// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

/**
 * Protobuf type {@code minipostgres.query.v1.Value}
 */
public final class Value extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minipostgres.query.v1.Value)
    ValueOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Value.class.getName());
  }
  // Use Value.newBuilder() to construct.
  private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Value() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_Value_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_Value_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            database.kernel.grpc.query.v1.Value.class, database.kernel.grpc.query.v1.Value.Builder.class);
  }

  private int valCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object val_;
  public enum ValCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INT_VAL(1),
    FLOAT_VAL(2),
    STRING_VAL(3),
    IS_NULL(4),
    VAL_NOT_SET(0);
    private final int value;
    private ValCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValCase forNumber(int value) {
      switch (value) {
        case 1: return INT_VAL;
        case 2: return FLOAT_VAL;
        case 3: return STRING_VAL;
        case 4: return IS_NULL;
        case 0: return VAL_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValCase
  getValCase() {
    return ValCase.forNumber(
        valCase_);
  }

  public static final int INT_VAL_FIELD_NUMBER = 1;
  /**
   * <code>int32 int_val = 1;</code>
   * @return Whether the intVal field is set.
   */
  @java.lang.Override
  public boolean hasIntVal() {
    return valCase_ == 1;
  }
  /**
   * <code>int32 int_val = 1;</code>
   * @return The intVal.
   */
  @java.lang.Override
  public int getIntVal() {
    if (valCase_ == 1) {
      return (java.lang.Integer) val_;
    }
    return 0;
  }

  public static final int FLOAT_VAL_FIELD_NUMBER = 2;
  /**
   * <code>float float_val = 2;</code>
   * @return Whether the floatVal field is set.
   */
  @java.lang.Override
  public boolean hasFloatVal() {
    return valCase_ == 2;
  }
  /**
   * <code>float float_val = 2;</code>
   * @return The floatVal.
   */
  @java.lang.Override
  public float getFloatVal() {
    if (valCase_ == 2) {
      return (java.lang.Float) val_;
    }
    return 0F;
  }

  public static final int STRING_VAL_FIELD_NUMBER = 3;
  /**
   * <code>string string_val = 3;</code>
   * @return Whether the stringVal field is set.
   */
  public boolean hasStringVal() {
    return valCase_ == 3;
  }
  /**
   * <code>string string_val = 3;</code>
   * @return The stringVal.
   */
  public java.lang.String getStringVal() {
    java.lang.Object ref = "";
    if (valCase_ == 3) {
      ref = val_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (valCase_ == 3) {
        val_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string string_val = 3;</code>
   * @return The bytes for stringVal.
   */
  public com.google.protobuf.ByteString
      getStringValBytes() {
    java.lang.Object ref = "";
    if (valCase_ == 3) {
      ref = val_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (valCase_ == 3) {
        val_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_NULL_FIELD_NUMBER = 4;
  /**
   * <code>bool is_null = 4;</code>
   * @return Whether the isNull field is set.
   */
  @java.lang.Override
  public boolean hasIsNull() {
    return valCase_ == 4;
  }
  /**
   * <code>bool is_null = 4;</code>
   * @return The isNull.
   */
  @java.lang.Override
  public boolean getIsNull() {
    if (valCase_ == 4) {
      return (java.lang.Boolean) val_;
    }
    return false;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valCase_ == 1) {
      output.writeInt32(
          1, (int)((java.lang.Integer) val_));
    }
    if (valCase_ == 2) {
      output.writeFloat(
          2, (float)((java.lang.Float) val_));
    }
    if (valCase_ == 3) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, val_);
    }
    if (valCase_ == 4) {
      output.writeBool(
          4, (boolean)((java.lang.Boolean) val_));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (valCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            1, (int)((java.lang.Integer) val_));
    }
    if (valCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(
            2, (float)((java.lang.Float) val_));
    }
    if (valCase_ == 3) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, val_);
    }
    if (valCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            4, (boolean)((java.lang.Boolean) val_));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof database.kernel.grpc.query.v1.Value)) {
      return super.equals(obj);
    }
    database.kernel.grpc.query.v1.Value other = (database.kernel.grpc.query.v1.Value) obj;

    if (!getValCase().equals(other.getValCase())) return false;
    switch (valCase_) {
      case 1:
        if (getIntVal()
            != other.getIntVal()) return false;
        break;
      case 2:
        if (java.lang.Float.floatToIntBits(getFloatVal())
            != java.lang.Float.floatToIntBits(
                other.getFloatVal())) return false;
        break;
      case 3:
        if (!getStringVal()
            .equals(other.getStringVal())) return false;
        break;
      case 4:
        if (getIsNull()
            != other.getIsNull()) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (valCase_) {
      case 1:
        hash = (37 * hash) + INT_VAL_FIELD_NUMBER;
        hash = (53 * hash) + getIntVal();
        break;
      case 2:
        hash = (37 * hash) + FLOAT_VAL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFloatVal());
        break;
      case 3:
        hash = (37 * hash) + STRING_VAL_FIELD_NUMBER;
        hash = (53 * hash) + getStringVal().hashCode();
        break;
      case 4:
        hash = (37 * hash) + IS_NULL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsNull());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static database.kernel.grpc.query.v1.Value parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.Value parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.Value parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.Value parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.Value parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static database.kernel.grpc.query.v1.Value parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.Value parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.Value parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static database.kernel.grpc.query.v1.Value parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static database.kernel.grpc.query.v1.Value parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static database.kernel.grpc.query.v1.Value parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static database.kernel.grpc.query.v1.Value parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(database.kernel.grpc.query.v1.Value prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minipostgres.query.v1.Value}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minipostgres.query.v1.Value)
      database.kernel.grpc.query.v1.ValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_Value_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              database.kernel.grpc.query.v1.Value.class, database.kernel.grpc.query.v1.Value.Builder.class);
    }

    // Construct using database.kernel.grpc.query.v1.Value.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      valCase_ = 0;
      val_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return database.kernel.grpc.query.v1.QueryServiceProto.internal_static_minipostgres_query_v1_Value_descriptor;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.Value getDefaultInstanceForType() {
      return database.kernel.grpc.query.v1.Value.getDefaultInstance();
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.Value build() {
      database.kernel.grpc.query.v1.Value result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public database.kernel.grpc.query.v1.Value buildPartial() {
      database.kernel.grpc.query.v1.Value result = new database.kernel.grpc.query.v1.Value(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(database.kernel.grpc.query.v1.Value result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(database.kernel.grpc.query.v1.Value result) {
      result.valCase_ = valCase_;
      result.val_ = this.val_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof database.kernel.grpc.query.v1.Value) {
        return mergeFrom((database.kernel.grpc.query.v1.Value)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(database.kernel.grpc.query.v1.Value other) {
      if (other == database.kernel.grpc.query.v1.Value.getDefaultInstance()) return this;
      switch (other.getValCase()) {
        case INT_VAL: {
          setIntVal(other.getIntVal());
          break;
        }
        case FLOAT_VAL: {
          setFloatVal(other.getFloatVal());
          break;
        }
        case STRING_VAL: {
          valCase_ = 3;
          val_ = other.val_;
          onChanged();
          break;
        }
        case IS_NULL: {
          setIsNull(other.getIsNull());
          break;
        }
        case VAL_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              val_ = input.readInt32();
              valCase_ = 1;
              break;
            } // case 8
            case 21: {
              val_ = input.readFloat();
              valCase_ = 2;
              break;
            } // case 21
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              valCase_ = 3;
              val_ = s;
              break;
            } // case 26
            case 32: {
              val_ = input.readBool();
              valCase_ = 4;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int valCase_ = 0;
    private java.lang.Object val_;
    public ValCase
        getValCase() {
      return ValCase.forNumber(
          valCase_);
    }

    public Builder clearVal() {
      valCase_ = 0;
      val_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>int32 int_val = 1;</code>
     * @return Whether the intVal field is set.
     */
    public boolean hasIntVal() {
      return valCase_ == 1;
    }
    /**
     * <code>int32 int_val = 1;</code>
     * @return The intVal.
     */
    public int getIntVal() {
      if (valCase_ == 1) {
        return (java.lang.Integer) val_;
      }
      return 0;
    }
    /**
     * <code>int32 int_val = 1;</code>
     * @param value The intVal to set.
     * @return This builder for chaining.
     */
    public Builder setIntVal(int value) {

      valCase_ = 1;
      val_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 int_val = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntVal() {
      if (valCase_ == 1) {
        valCase_ = 0;
        val_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>float float_val = 2;</code>
     * @return Whether the floatVal field is set.
     */
    public boolean hasFloatVal() {
      return valCase_ == 2;
    }
    /**
     * <code>float float_val = 2;</code>
     * @return The floatVal.
     */
    public float getFloatVal() {
      if (valCase_ == 2) {
        return (java.lang.Float) val_;
      }
      return 0F;
    }
    /**
     * <code>float float_val = 2;</code>
     * @param value The floatVal to set.
     * @return This builder for chaining.
     */
    public Builder setFloatVal(float value) {

      valCase_ = 2;
      val_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float float_val = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloatVal() {
      if (valCase_ == 2) {
        valCase_ = 0;
        val_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>string string_val = 3;</code>
     * @return Whether the stringVal field is set.
     */
    @java.lang.Override
    public boolean hasStringVal() {
      return valCase_ == 3;
    }
    /**
     * <code>string string_val = 3;</code>
     * @return The stringVal.
     */
    @java.lang.Override
    public java.lang.String getStringVal() {
      java.lang.Object ref = "";
      if (valCase_ == 3) {
        ref = val_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valCase_ == 3) {
          val_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string_val = 3;</code>
     * @return The bytes for stringVal.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValBytes() {
      java.lang.Object ref = "";
      if (valCase_ == 3) {
        ref = val_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valCase_ == 3) {
          val_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string_val = 3;</code>
     * @param value The stringVal to set.
     * @return This builder for chaining.
     */
    public Builder setStringVal(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      valCase_ = 3;
      val_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string string_val = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringVal() {
      if (valCase_ == 3) {
        valCase_ = 0;
        val_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string string_val = 3;</code>
     * @param value The bytes for stringVal to set.
     * @return This builder for chaining.
     */
    public Builder setStringValBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      valCase_ = 3;
      val_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>bool is_null = 4;</code>
     * @return Whether the isNull field is set.
     */
    public boolean hasIsNull() {
      return valCase_ == 4;
    }
    /**
     * <code>bool is_null = 4;</code>
     * @return The isNull.
     */
    public boolean getIsNull() {
      if (valCase_ == 4) {
        return (java.lang.Boolean) val_;
      }
      return false;
    }
    /**
     * <code>bool is_null = 4;</code>
     * @param value The isNull to set.
     * @return This builder for chaining.
     */
    public Builder setIsNull(boolean value) {

      valCase_ = 4;
      val_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_null = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsNull() {
      if (valCase_ == 4) {
        valCase_ = 0;
        val_ = null;
        onChanged();
      }
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minipostgres.query.v1.Value)
  }

  // @@protoc_insertion_point(class_scope:minipostgres.query.v1.Value)
  private static final database.kernel.grpc.query.v1.Value DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new database.kernel.grpc.query.v1.Value();
  }

  public static database.kernel.grpc.query.v1.Value getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Value>
      PARSER = new com.google.protobuf.AbstractParser<Value>() {
    @java.lang.Override
    public Value parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Value> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Value> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public database.kernel.grpc.query.v1.Value getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

