// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: query_service.proto
// Protobuf Java Version: 4.29.3

package database.kernel.grpc.query.v1;

public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minipostgres.query.v1.Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 int_val = 1;</code>
   * @return Whether the intVal field is set.
   */
  boolean hasIntVal();
  /**
   * <code>int32 int_val = 1;</code>
   * @return The intVal.
   */
  int getIntVal();

  /**
   * <code>float float_val = 2;</code>
   * @return Whether the floatVal field is set.
   */
  boolean hasFloatVal();
  /**
   * <code>float float_val = 2;</code>
   * @return The floatVal.
   */
  float getFloatVal();

  /**
   * <code>string string_val = 3;</code>
   * @return Whether the stringVal field is set.
   */
  boolean hasStringVal();
  /**
   * <code>string string_val = 3;</code>
   * @return The stringVal.
   */
  java.lang.String getStringVal();
  /**
   * <code>string string_val = 3;</code>
   * @return The bytes for stringVal.
   */
  com.google.protobuf.ByteString
      getStringValBytes();

  /**
   * <code>bool is_null = 4;</code>
   * @return Whether the isNull field is set.
   */
  boolean hasIsNull();
  /**
   * <code>bool is_null = 4;</code>
   * @return The isNull.
   */
  boolean getIsNull();

  database.kernel.grpc.query.v1.Value.ValCase getValCase();
}
